### ISSUE TITLE
Balancers page easier to find

### ISSUE THREAD

**Issue by daddycr0n** [AnthorNet/SC-InteractiveMap#10]
Hi,

The following page has been very useful to me, maybe it could be made easier to find on the site for others that haven't been given a direct link like me? 
https://satisfactory-calculator.com/en/balancers

Cheers

**Comment by AnthorNet** [comment]
To be fair, it was to be reomved :D

**Comment by daddycr0n** [comment]
Fair enough :)

**Comment by AnthorNet** [comment]
Closing it for now, will may be add them back when adding the color tool page.
