### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by ZeDanish** [AnthorNet/SC-InteractiveMap#100]
This started happening on 17/06/2021. I tried uploading every saved file I had. None of them seems to be working anymore. It was working well for 2 weeks of use. 
![image](https://user-images.githubusercontent.com/86049685/122369486-d1617f00-cf90-11eb-9804-2c613457be5e.png)

**Comment by AnthorNet** [comment]
Are you using adblock? 
Any console error?

**Comment by ZeDanish** [comment]
yes I used Adblock. I disabled it now its working. Thank you!

**Comment by ml0130** [comment]
As of 17-06-21 @ 10:42 PST this problem is still happening even with ad block turned off
![image](https://user-images.githubusercontent.com/27445711/122447627-cab71580-cf58-11eb-9b9a-76c3adeeaa29.png)

**Comment by AnthorNet** [comment]
I need your console browser when it's happening.

**Comment by ml0130** [comment]
initial site load with adblock on
![image](https://user-images.githubusercontent.com/27445711/122448725-ecfd6300-cf59-11eb-8785-b5e94bb5094d.png)

Loading save w/ adblock on
![image](https://user-images.githubusercontent.com/27445711/122448888-174f2080-cf5a-11eb-8676-8fb51901268a.png)

initial site load with adblock off
![image](https://user-images.githubusercontent.com/27445711/122449127-5da47f80-cf5a-11eb-94db-33b0c91bca1c.png)

loading save w/ adblock off
![image](https://user-images.githubusercontent.com/27445711/122449267-888ed380-cf5a-11eb-84c8-04b022006663.png)
![image](https://user-images.githubusercontent.com/27445711/122449301-92183b80-cf5a-11eb-87d4-0921a56f5930.png)
