### ISSUE TITLE
Request: Able to Verify Rail/Train Layouts and connectors

### ISSUE THREAD

**Issue by VitsNZ** [AnthorNet/SC-InteractiveMap#102]
Greetings Team, 

More of a feature request to be able to verify that the rail network is valid, or if when its not, isolate and identify where the connectors may be incorrect.. That is... unable to find next stop isnt a helpful in-game diag tool.

**Comment by AnthorNet** [comment]
Not the best  but you can now hover a railway to see it's connected rails.
https://github.com/AnthorNet/SC-InteractiveMap/commit/1d05acb6b2bee974e7029dad4457a78ce52cce16
