### ISSUE TITLE
Map Rotation

### ISSUE THREAD

**Issue by THECorranHorn** [AnthorNet/SC-InteractiveMap#103]
Would be really nice to be able to rotate the entire map clockwise/counterclockwise if possible, if not feel free to delete/ignore

**Comment by AnthorNet** [comment]
Selection can already rotate stuff.

**Comment by THECorranHorn** [comment]
That's not what I meant, I meant rotating the map not items. Just like you can do with a mobile maps app or Google Earth.

**Comment by AnthorNet** [comment]
Ha ok, yeah not sure it can be done with the current engine we use

**Comment by THECorranHorn** [comment]
K, if you could reopen this and see if it's possible I'd really appreciate it. Being able to rotate the whole map together like that would be really REALLY helpful if it's possible.

**Comment by AnthorNet** [comment]
Checked and the rotation aren't part of the engine.
It would require to rewrite a lot of custom event stuff positioning.
