### ISSUE TITLE
Feature Request: (non urgent) - Recipes in Use stat

### ISSUE THREAD

**Issue by VitsNZ** [AnthorNet/SC-InteractiveMap#105]
Greetings,

Low priority, was just a working thought if the interactive maps, stats, could show which recipes are in use, and if able to, when clicking on the "inferior" previous life choices, to identify where those recipes are being used.
Was just a Sunday afternoon though.
Regards
dave

**Comment by AnthorNet** [comment]
Would that work in the building listing?

**Comment by VitsNZ** [comment]
OMG.... That's trucking awesome. 
I must say, my satisfactory addiction started just a year ago when an ex workmate said it was available on Steam.
I soon discovered your web tool and I can't imagine how many hours you have put into this project.
From a humble satisfactory addicted user from Auckland, New Zealand.. Thank You Sir

**Comment by AnthorNet** [comment]
From what I see the building list already contains that information, but I could expand it with sorting and filtering.

**Comment by VitsNZ** [comment]
That would be cool.  Geographical clumping as a sort-filter by Biome would be a bonus. :)
All non urgent as well.. just a nice to have feature
