### ISSUE TITLE
how come everytime i load map into the game it will be a new map?

### ISSUE THREAD

**Issue by DavidChiu0418** [AnthorNet/SC-InteractiveMap#106]
![image](https://user-images.githubusercontent.com/654353/126214420-98e45525-0660-4bde-8f53-c2a3b1794052.png)

what happen?

**Comment by AnthorNet** [comment]
I'm normally just appending to the original save name.
Could you upload your save?

**Comment by DavidChiu0418** [comment]
https://www.sendspace.com/file/z5gqhv
( ˘•ω•˘ )◞here

**Comment by DavidChiu0418** [comment]
i havent play this game almost a year
it didnt happen b4...

**Comment by AnthorNet** [comment]
Looks like the characters in the session name are causing issue.
I'll take a closer look to see why and how.
