### ISSUE TITLE
Color options not saving

### ISSUE THREAD

**Issue by SMERKIN5000** [AnthorNet/SC-InteractiveMap#11]
When you change a color slot for the map and close the window, the color is not save.

Also, typing in the boxes makes things happen in the background map, like I think 6 or 7 causes a zoom out.

**Comment by AnthorNet** [comment]
I could not reproduce the not saving thing, by any chance, may be you haven't unlocked the color slots in game before trying to change them in SCIM?

**Comment by AnthorNet** [comment]
![image](https://user-images.githubusercontent.com/654353/103092150-9b9d9800-45f6-11eb-8656-41623c31ebbd.png)

**Comment by AnthorNet** [comment]
https://github.com/AnthorNet/SC-InteractiveMap/commit/245895b01e98a8f573a216a62dc44c4cbf39fe81

**Comment by SMERKIN5000** [comment]
![image](https://user-images.githubusercontent.com/60308025/103106583-c9ccb780-468a-11eb-9ebb-d3583b7995eb.png)
I do get the locked error on the site now, however it does show I've unlocked it. I'll try in the next stream to see if making a gun fixes it. I had a color gun stored in a container but it was a blueprint brought across from another save so even though I've done fresh MAM unlocks perhaps because I've not made a gun it's not registered.

**Comment by AnthorNet** [comment]
It is highly possible the slots are generated after using or crafting the color gun.
So may be the warning should be updated to reflect the correct status.

I could try to generate them also.

**Comment by AnthorNet** [comment]
Updated the warning for now: https://github.com/AnthorNet/SC-InteractiveMap/commit/2e06fdd8cf42bebf341729e343f12840fa9924be

**Comment by SMERKIN5000** [comment]
The problem seems to be tied to actually editing a color slot. I tried making a new gun, created a cartridge and it still didn't work. Once I edited a slot and saved, it uploaded and updated OK.

**Comment by AnthorNet** [comment]
Need to test if this fix the issue.

**Comment by SMERKIN5000** [comment]
Just tested and the problem is now resolved.
