### ISSUE TITLE
Feature Request: Space Elevator inventory display

### ISSUE THREAD

**Issue by SignpostMarv** [AnthorNet/SC-InteractiveMap#110]
While #6 concerned itself with setting/resetting the current phase of the space elevator, this feature request concerns itself with displaying the contents of the unshipped elevator freight, in a similar fashion to how storage containers and item producers display their contents.

**Comment by AnthorNet** [comment]
Could you post a screenshot of the screen?

**Comment by SignpostMarv** [comment]
I would've posted a screenshot, but didn't catch the alert- guessing you no longer need the screenshot?
