### ISSUE TITLE
Feature Request: Display power consumption in more places

### ISSUE THREAD

**Issue by SignpostMarv** [AnthorNet/SC-InteractiveMap#113]
- [ ] Statistics Panel
- [ ] Selection overview

Currently trying to track down what portion of my factory is consuming a relatively high amount of power, tracking it down manually is an exercise in frustration.

**Comment by TheOrigonalHieraco** [comment]
Maybe have an electrical equivalent of the pipes “this segment”  break up the power grid with switch like boxes that allow electrical pass through, but also reports the status from that point to the next box.

I think we’d need to sequentially number the boxes so box #1 reports consumption/production between box 1 and box 2 and box 3 reports status between 2 and 3 etc.  As I think about this we’d need a way to track multiple branches so if point 8 breaks off into five branches, then we’d need to be able to report status between 9 and 8, point 10 and 8, 11 and 8, 12 and 8, and point 13 and 8. 

Perhaps alllow the user to assign the identifier to each box, with a check that tells you if the identifier is already in use.


It’s a lot, but that’s just off the top of my head. Other suggestions for implementing are welcome.

**Comment by AnthorNet** [comment]
Closing as power circuits stats have been added and also the power flow from buildings
