### ISSUE TITLE
Arm Slots Unlock Error

### ISSUE THREAD

**Issue by THECorranHorn** [AnthorNet/SC-InteractiveMap#118]
When unlocking all research items for a save, the scim incorrectly adds a 6th arm slot, the most allowed vanilla is 5.

**Comment by AnthorNet** [comment]
I think we allow 9? And the game loads correctly?

**Comment by THECorranHorn** [comment]
Yes the game loads correctly, but when unlocking everything with the scim I'd suggest it only configure the arm slot # to 5 instead of 6 like what it does now since 5 is the standard vanilla max.

**Comment by AnthorNet** [comment]
It should not go further if it wasn't touch in the options before unlocking.
