### ISSUE TITLE
"Debug" factories in the online editor

### ISSUE THREAD

**Issue by Angel0fDarkness** [AnthorNet/SC-InteractiveMap#119]
While using the Statistics tool, you can already get a basic understanding whether your factories are laid our correctly and you produce enough goods for further production.
It would be cool if this could be broken down onto the belt system itself, telling you whether enough materials are coming inbound on the belt (at least where they are connected to buildings producing items) to feed all the factories taking things from that belt.

At least I found it very difficult (still quite a beginner in Satisfactory) to debug problems of my factories and find out why there isnt full productivity of certain factories.
Here you could get a different belt color or some other indicator on where to look :)
Also like if you have a Mk2 belt somewhere in between you Mk3 belt system or something..

**Comment by AnthorNet** [comment]
Too much work I'm afraid!
