### ISSUE TITLE
The contrast on the switch branch button is really bad

### ISSUE THREAD

**Issue by rphsoftware** [AnthorNet/SC-InteractiveMap#120]
With the small text + the background and text color being close to each other, the button can be hard to notice and is hard to read in case the user has poor eyesight.

Chrome dev tools screenshot:
![image](https://user-images.githubusercontent.com/11350302/139333544-b27731a2-832e-4217-845b-56e3b45d13d7.png)

I believe a fix to this would be making the button's background a shade of red, rather than orange, which while going out of the branding, would make the button much more accessible.

**Comment by AnthorNet** [comment]
Should be better now
