### ISSUE TITLE
Loading map stuck at "Rendering: 0%"

### ISSUE THREAD

**Issue by Synxis** [AnthorNet/SC-InteractiveMap#123]
This is for the interactive map.

As of today (I don't know for previous versions), loading a map fails, the process is stuck at "Rendering: 0%".
I tried with multiple maps, both the latest version of my save and monthes-old saves exhibited the same behavior. I know the previous save worked fine with SCIM.

Here is the output of the console:

    Inflated: 806 chunks...
    Parsing: 112889 objects...
    Parsing: 112889 entities...
    Parsing: 844 collectables...
    loadSave : 13038 ms - chronomètre arrêté

    Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
        getBuildingDataFromClassName              https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        parseObject                               https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        parseObjects                              https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        parseObjects                              https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        renderObjects                             https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        promise callback*renderObjects            https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        loadDetailedModels                        https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        jQuery                                    8
        loadDetailedModels                        https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        promise callback*loadDetailedModels       https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        draw                                      https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        jQuery                                    8
        draw                                      https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        promise callback*draw/<                   https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        parseObjectsV5                            https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1
        setTimeout handler*parseObjectsV5/</</<   https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1635613434:1

Thanks !

**Comment by AnthorNet** [comment]
My bad :) EA data wasn't working with the new release of the map

**Comment by Synxis** [comment]
Thanks for the very fast fix ! It works now :)
