### ISSUE TITLE
Feature Request: Show poison pillars on the map

### ISSUE THREAD

**Issue by 9avid** [AnthorNet/SC-InteractiveMap#124]
If poison pillars are displayed on the map, it will be much more handy. With their help it will be possible to orientate on the map. And also it will be possible to plan your route in advance knowing their location.

**Comment by AnthorNet** [comment]
That's not a data we can get hands on yet

**Comment by 9avid** [comment]
How about collecting the coordinates of each pillar manually?
I could help too

**Comment by AnthorNet** [comment]
There was some I've been provided, mainly in Grassland

[
    ['x'=>19018.953125,'y'=>113664.046875,'z'=>26686.367188],
    ['x'=>8246.667969,'y'=>112270.171875,'z'=>27079.095703],
    ['x'=>10675.386719,'y'=>117711.320313,'z'=>26429.820313],
    ['x'=>16075.824219,'y'=>107094.453125,'z'=>26813.134766],
    ['x'=>16895.787109,'y'=>109727.132813,'z'=>26884.412109],
    ['x'=>9484.293945,'y'=>115254.718750,'z'=>26775.548828],
    ['x'=>13593.602539,'y'=>109754.585938,'z'=>26776.921875],
    ['x'=>10562.180664,'y'=>110271.242188,'z'=>26704.853516],
    ['x'=>16870.601563,'y'=>112032.890625,'z'=>26707.103516],
    ['x'=>10486.452148,'y'=>112699.953125,'z'=>26886.751953],
    ['x'=>12067.867188,'y'=>115495.210938,'z'=>26323.019531],
    ['x'=>12927.744141,'y'=>112355.179688,'z'=>26512.884766],
    ['x'=>14573.337891,'y'=>117431.804688,'z'=>26355.310547],
    ['x'=>19527.863281,'y'=>124829.484375,'z'=>27410.669922],
    ['x'=>17248.339844,'y'=>125072.007813,'z'=>27319.234375],
    ['x'=>17879.697266,'y'=>123468.171875,'z'=>27263.003906],
    ['x'=>14095.370117,'y'=>123453.343750,'z'=>25616.126953],
    ['x'=>19264.035156,'y'=>121289.070313,'z'=>25317.615234],
    ['x'=>17725.488281,'y'=>118393.750000,'z'=>25334.687500],
    ['x'=>15588.491211,'y'=>121189.664063,'z'=>25486.152344],
    ['x'=>14733.298828,'y'=>111445.765625,'z'=>26629.783203],
    ['x'=>15353.102539,'y'=>114747.648438,'z'=>26444.791016],
    ['x'=>44582.304688,'y'=>78048.828125,'z'=>23617.890625],
    ['x'=>39740.218750,'y'=>73507.578125,'z'=>23535.621094],
    ['x'=>37869.660156,'y'=>75075.437500,'z'=>23249.408203],
    ['x'=>36012.164063,'y'=>78667.062500,'z'=>23134.787109],
    ['x'=>37963.820313,'y'=>82317.898438,'z'=>27058.125000],
    ['x'=>41803.113281,'y'=>74667.960938,'z'=>23664.308594],
    ['x'=>42734.289063,'y'=>77375.531250,'z'=>25777.205078],
    ['x'=>39869.140625,'y'=>83521.273438,'z'=>26264.210938],
    ['x'=>41573.902344,'y'=>80011.468750,'z'=>27058.958984],
    ['x'=>40327.562500,'y'=>75541.835938,'z'=>26259.015625],
    ['x'=>38321.957031,'y'=>77982.304688,'z'=>26841.958984],
    ['x'=>39566.531250,'y'=>80274.398438,'z'=>27012.888672],
    ['x'=>-41301.445313,'y'=>82714.585938,'z'=>26575.548828],
    ['x'=>-41298.835938,'y'=>84149.890625,'z'=>23859.386719],
    ['x'=>-42701.421875,'y'=>79672.414063,'z'=>24726.996094],
    ['x'=>-44771.476563,'y'=>80967.945313,'z'=>24718.593750],
    ['x'=>-47137.253906,'y'=>85065.773438,'z'=>26655.123047],
    ['x'=>-40118.156250,'y'=>81284.070313,'z'=>24625.498047],
    ['x'=>-45251.250000,'y'=>86644.875000,'z'=>26806.625000],
    ['x'=>-43150.695313,'y'=>85252.351563,'z'=>26693.738281],
    ['x'=>-44387.414063,'y'=>82931.421875,'z'=>26701.787109],
    ['x'=>22987.359375,'y'=>78077.828125,'z'=>22735.623047],
    ['x'=>25661.755859,'y'=>70323.929688,'z'=>22810.408203],
    ['x'=>28389.162109,'y'=>75515.125000,'z'=>22835.392578],
    ['x'=>19972.054688,'y'=>73323.359375,'z'=>22658.751953],
    ['x'=>27307.988281,'y'=>72927.726563,'z'=>22762.941406],
    ['x'=>21643.880859,'y'=>75839.703125,'z'=>22694.855469],
    ['x'=>26259.054688,'y'=>75079.679688,'z'=>22745.796875],
    ['x'=>25022.847656,'y'=>72924.328125,'z'=>22771.695313],
    ['x'=>22220.859375,'y'=>72112.304688,'z'=>22768.345703],
]

**Comment by 9avid** [comment]
Did you save your coordinates with some utility or copied it from somewhere?

**Comment by AnthorNet** [comment]
They were provided by CSS at some point, but that was around a year ago, so not even sure it is still up to date.
May be see with modding community if they can extract them somehow.
