### ISSUE TITLE
[BUG] (Experimental) Cannot change swatch of new Concrete Foundations/Ramps

### ISSUE THREAD

**Issue by budn8** [AnthorNet/SC-InteractiveMap#126]
This is the context menu that shows when right-clicking the new concrete material foundations in the Interactive Map:

![image](https://user-images.githubusercontent.com/39417521/140010530-ff9d63b1-a28b-4d17-8326-57327471da56.png)

It is missing the "Update color swatch" option which is usually under the "Update position" option for normal foundations

**Comment by AnthorNet** [comment]
Fixed
