### ISSUE TITLE
Syncronize Geothermal generators

### ISSUE THREAD

**Issue by NiklasRichter2222** [AnthorNet/SC-InteractiveMap#127]
would it be possible to implement a feature to change the timings of the geothermal generators so that they alternate or are all synchronized or just custom

**Comment by AnthorNet** [comment]
I think there's an offset but that would require some tests in game to check

**Comment by AnthorNet** [comment]
It should be mVariablePowerProductionCycleOffset

**Comment by kajahama** [comment]
It's the offset time in seconds between 0 <= X < 60 with full number of decimals the FP32 float type allows.
So should be that 0 is allowed, 60 probably isn't but just under it is.

Randomized at placement moment it seems.
Doesn't care about anything when tried to sync with help of a timer.

When to same grade geothermal generators are 30 seconds out of sync (so 0 and 30, 15 and 45 etc.) their fluctuations will cancel out perfectly.
And to lower grade ones with same number will cancel out with one next higher grade one at 30 seconds offset.

Was coming to request ability to edit the number.

**Comment by kajahama** [comment]
Do you need more information or testing to implement quick UI to change the number after right clicking a geothermal generator?
Even just being able to manually set the mVariablePowerProductionCycleOffset for each generator to whole numbers between 0 and 59 would be nice.

**Comment by warp9pnt9** [comment]
Was this ever implemented?  Or subsequently removed?  I can't seem to find any way to synchronize or edit values in SCIM.  Advanced Debug shows the value...

**Comment by warp9pnt9** [comment]
Tested, seems to be working.  Had 6 nodes with previously built geysers of different purities.  Changed all 6 to pure (range 200-600 MW, average 400 MW).  Also tested offset code.  Set each pair to 15 and 45 (30 seconds offset, 1/2 of the 60s cycle).  Seeing flat power line (the 6 gens are on isolated grid by themselves), 2,400 MW (6 * 400 MW).  Both features seem to work ok now.  Thanks for implementing!
