### ISSUE TITLE
Editing world causes all pipes to turn pink unless changed to another color preset

### ISSUE THREAD

**Issue by RandomGgames** [AnthorNet/SC-InteractiveMap#13]
As the title suggests, when a new world or old world is loaded into the interactive map, after changing some settings, all water pipes turn pink. I haven't noticed this happen to other objects yet. Choosing another color in the editor works fine, however the default orange and gray do not appear as that. See the 3 SAV files as well as the video of me creating a new world and loading it into the map, than making some slight modifications and downloading it (Ingore black areas of video, I wait for the screen capture to switch since it's going from fullscreen to windowed and takes a moment. I don't do anything within those time spans.

3 Save files .zip
[PinkPipeTest savs x3.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/5759349/PinkPipeTest.savs.x3.zip)

Video: https://youtu.be/pl-UofPemG0

**Comment by AnthorNet** [comment]
It looks like the default color is not working correctly, not sure why..

**Comment by AnthorNet** [comment]
Unlocking "Coal power" alone seems to be causing the issue.
Need to run more tests to see which schematic is missing and causing the bug.

**Comment by AnthorNet** [comment]
Can you test if that fixes the issue?

**Comment by RandomGgames** [comment]
Seems to be good!

**Comment by AnthorNet** [comment]
Just in case you need to fix your other save, under Options > Color Slots, you should be able to reset the default pipe color, or even switch to a new one :p
