### ISSUE TITLE
Weird icon on my map after saving 

### ISSUE THREAD

**Issue by karyonite** [AnthorNet/SC-InteractiveMap#134]
![what's this](https://user-images.githubusercontent.com/94323903/141699825-25801a74-46d3-4b82-87df-b0583912d4ac.jpg)
[savegame.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/7534738/savegame.zip)

After loading my downloaded savegame I have a weird pink icon that I don''t know how to get rid of. There seems to be nothing there.

**Comment by AnthorNet** [comment]
Can you elaborate on what you have done on the map?

**Comment by karyonite** [comment]
Of course! I used two blueprints from other saves and loaded them into this save.
Then I used the "delete crate" option to remove a few unnecessary crates.
This is the end-result. I hope that helps, if that doesn't then please let me know what else I can tell you.

**Comment by Artelis** [comment]
Curious. I've been seeing the same thing on my map for a while now and haven't been able to figure out why - and it seems to be in exactly the same spot. Too many hours sunk into this save to figure out when / what could've caused it, sadly!

According to the in-game map filters, it's a train station (with no name), but in SCIM there's nothing there.

**Comment by AnthorNet** [comment]
Position is [0, 0], at the center of the map.
That said I still haven't found anything in the save that could lead to that.
