### ISSUE TITLE
Buildings no longer showing on map

### ISSUE THREAD

**Issue by karyonite** [AnthorNet/SC-InteractiveMap#135]
After opening a save I downloaded I can no longer see buildings on my map in-game.

[savegame.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/7534740/savegame.zip)

**Comment by AnthorNet** [comment]
Can you elaborate on what you have done on the map?

**Comment by karyonite** [comment]
Of course! I used two blueprints from other saves and loaded them into this save.
Then I used the "delete crate" option to remove a few unnecessary crates.
This is the end-result. I hope that helps, if that doesn't then please let me know what else I can tell you.

**Comment by karyonite** [comment]
Very sorry, this was just a misunderstanding on my part. It felt confusing not to seen any buildings/structures on the map, but while the Calculator has that...the actual ingame map does not show buildings/train rails, etc.
