### ISSUE TITLE
Version 5 map updates need included.

### ISSUE THREAD

**Issue by Venivdvici** [AnthorNet/SC-InteractiveMap#138]
Title says it all. Some ores sites may have been moved, removed or added. At least one drop pod is no longer as marked. (I haven't found a new one yet though.)

**Comment by AnthorNet** [comment]
Map is updated since experimental.
Apart if you found a specific node type that have changed, they are automatically extracted at each update.

Some drop does have changed ID which can explain their status. You can go open them again.
