### ISSUE TITLE
Bug: impossible to input negative numbers into altitude filter's fields

### ISSUE THREAD

**Issue by alzhur** [AnthorNet/SC-InteractiveMap#140]
Looks like some aggressive input checker applied, checking input after every keystroke and replacing all string with "0", if it's not a number.
First symbol for negative number, "-" is not a number by itself, and so, is auto-replaced with "0".
As a result - impossible to input negative numbers into that 2 fields.

Workaround: type number elsewhere (Notepad etc), copy it, put cursor into input field of altitude filter, Ctrl-A, Ctrl-V.
But this workaround is boring to use.

**Comment by AnthorNet** [comment]
Agree on that, I believe you can also type positive, then prepend the negative part.
I'll check what can be done about that this week.

**Comment by AnthorNet** [comment]
Should be ok now?
