### ISSUE TITLE
Something went wrong while we were trying to parse your save game

### ISSUE THREAD

**Issue by HellFroze** [AnthorNet/SC-InteractiveMap#142]
Since the latest updates, I have had problems loading my save game into the interactive map. I get an error message relating to a parse error. I have attached a zipped copy of my save file.
[HellFroze exp II.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/7659125/HellFroze.exp.II.zip)

**Comment by AnthorNet** [comment]
Hi, make sure you refresh your cache as you save is loading fine in the current release.

**Comment by HellFroze** [comment]
My apologies. This is what happens when you try to do things late at night. I sent you the wrong savegame. I have attached the one I am having problems with. Thanks for your help.

William

**Comment by AnthorNet** [comment]
Hey, no trouble, don't think the attachment went to GitHub.
