### ISSUE TITLE
Bug: Selectively disabling display of Foundation types does not persist on reload even though UI shows them disabled.

### ISSUE THREAD

**Issue by TheSkunkMonkey** [AnthorNet/SC-InteractiveMap#144]
Reproduction:

Load a map.
Selectively disable some Foundation types in the Foundation layer.
Reload the map.
Foundation layer UI shows the previous selections as still disabled yet they show on the map.

Turning them on and off again corrects the issue.

Expected behavior would be to have them all reset in the UI or have the map display per the settings.

**Comment by AnthorNet** [comment]
Ooopsie ! Dont reload, fixed :p
Nah jokii, I'll fix that tomorrow morning ;) thanks for reporting it.
