### ISSUE TITLE
Feature request: add option to align items to global grid

### ISSUE THREAD

**Issue by alzhur** [AnthorNet/SC-InteractiveMap#147]
Subj, maybe as option for "Update position" and "Offset selected items positions".
With minor exclusions maybe, like not moving miners, extractors etc at all, or moving them only vertically.

**Comment by Sereri** [comment]
If possible, it would also be nice to have an option to align the global grid to a foundation

**Comment by alzhur** [comment]
I have not tested this new feature yet, but I have 2 useful (I hope) suggestions:
1. Commit description says "Add align to world grid to Foundation/Ramps/Roofs". My idea was a bit different: use foundation/ramp/roof (maybe only NWSE-aligned one) to calculate offset, and after that, use this offset to move all selected items. Maybe, with some exclusions for miners etc.
2. For 1-meter variants of foundations/ramps/roofs you should apply 0.5 m vertical offset to compensate use of mid-point for snapping.
More info about issue with vertical grid alignment:
https://www.youtube.com/watch?v=JMq5ippH5q0
https://www.reddit.com/r/SatisfactoryGame/comments/r3i94s/small_discovery_about_vertical_world_grid/
https://questions.satisfactorygame.com/post/6196c7a0831c85205235f4fd

**Comment by AnthorNet** [comment]
1) Not sure how feasible it would be
2) I'm trying to follow the in-game grid as much as possible. Will see in the future if we need to bypass that or if it get fixed.

**Comment by Sereri** [comment]
@AnthorNet thank you for adding this feature. After trying it with my map, I have to say it doesn't work as I was expecting.
It turns
![image](https://user-images.githubusercontent.com/803440/200936168-c8835dfe-ae53-4f4c-9ed7-8ee0f43da013.png)
Into
![image](https://user-images.githubusercontent.com/803440/200936825-35ccd0db-8c07-4cfd-95fe-8aafe3b39028.png)

I'm not sure why I thought it would also align the rotation of the foundations to ... i don't know, north?

Would i be possible to add that, maybe as a checkbox or something?

**Comment by AnthorNet** [comment]
That would not fix your problem, as each foundation would be rotated, not the whole selection.
For that you would need to fix your design first by rotation the selection.
