### ISSUE TITLE
Context menu on player only shows Host and Adv Debug

### ISSUE THREAD

**Issue by DTG123** [AnthorNet/SC-InteractiveMap#149]
I was doing some editing and had to move player(me) out of the way. Went to move and the right click context menu and no way to move player.

**Comment by DTG123** [comment]
no explanation why this closed?

**Comment by AnthorNet** [comment]
There is a commit fixing you issue with the description of what was done.
Ha e you tried checking the player menu again?

**Comment by DTG123** [comment]
yep works as intended now. TY
