### ISSUE TITLE
Memory optimisation

### ISSUE THREAD

**Issue by destombesl** [AnthorNet/SC-InteractiveMap#150]
Now it's not possible tot use more than 4gb ram it's not enough for the bigger maps. Love to request some memory optimisation
One a split up process

**Comment by AnthorNet** [comment]
Should be better now with the medium quality settings.
Otherwise optimisation are taking place as I go ^^ But not much that can be done.

**Comment by destombesl** [comment]
thank you very much

Op di 1 mrt. 2022 10:44 schreef AnthorNet ***@***.***>:
