### ISSUE TITLE
Oil nodes with Mk++ mod

### ISSUE THREAD

**Issue by HellFroze** [AnthorNet/SC-InteractiveMap#153]
When I place the Oil Extractor Mk2 from the Mk++ mod, the nodes no longer show as occupied on the interactive map. Can this be corrected?

![Mk++ oil nodes](https://user-images.githubusercontent.com/95612266/147169692-37274ce9-64b0-4113-b278-adb7aaab770f.jpg)

**Comment by AnthorNet** [comment]
Please link an example save ;)

**Comment by HellFroze** [comment]
As requested. Nodes are north of the main floor, across the ditch.
[HellFroze exp.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/7771223/HellFroze.exp.zip)
.

**Comment by HellFroze** [comment]
sorry, wrong button.

**Comment by AnthorNet** [comment]
It's because the mod author didn't fill the correct category for the buildings, and the extraction rates.
