### ISSUE TITLE
Feature Suggestion: Bulkedit beacons

### ISSUE THREAD

**Issue by YetAnotherGerrit** [AnthorNet/SC-InteractiveMap#157]
It would be great to have a small tool to quickly edit all your beacon's names/colors. Maybe in a list-view?

**Comment by AnthorNet** [comment]
Normally be on edition is present with right click?

**Comment by syskill** [comment]
What is "be on edition"?

**Comment by AnthorNet** [comment]
Sorry mobile, there's no edition right now, so text and color is noted :)

**Comment by syskill** [comment]
Beacon text and color can be found in the data structure under "Advanced Debug", but there's no way to edit them.

![Beacon right click menu](https://user-images.githubusercontent.com/93612/166816771-c8fbb738-8eb1-413f-bd90-e67a70baa9f6.png)

**Comment by AnthorNet** [comment]
I know :D
I was certain it was already added. :P

I'll get on it soon

**Comment by YetAnotherGerrit** [comment]
Hey @AnthorNet thank you a ton for the single beacon edit-function! This already helps a lot. Is a list view/editor still on the table?

**Comment by YetAnotherGerrit** [comment]
Okay, nevermind... https://www.youtube.com/watch?v=2vAUX3YLH-c

**Comment by AnthorNet** [comment]
Yeah there will be some rework to do, so I'll close this one for now ;)
