### ISSUE TITLE
Feature Suggestion: Railway map

### ISSUE THREAD

**Issue by YetAnotherGerrit** [AnthorNet/SC-InteractiveMap#158]
It would be awesome to have an automatically generated railway-system map out of a save-file, like a cities subway-station-map. So just with rail-tracks, railway-stations (and their displayed label).

**Comment by CeeJay-YVR** [comment]
Good idea.  I have a spreadsheet but it is not as good as a map.  It would also be great for hypertube stations as well as drone stations
Thanks
