### ISSUE TITLE
Feature/Bug? Download map not available when using ?url=

### ISSUE THREAD

**Issue by vStone** [AnthorNet/SC-InteractiveMap#159]
It seems that the download map button is only available if you manually load a save game.

**Comment by AnthorNet** [comment]
Feature, it was done to avoid save stealing, but may ber it's a non sense?

**Comment by vStone** [comment]
Maybe a server header that allows saving?

**Comment by AnthorNet** [comment]
You can add &allowRemoteDownload=true to the URL ;)
