### ISSUE TITLE
Lake Forest 2 Forest Lake "biome" update

### ISSUE THREAD

**Issue by THECorranHorn** [AnthorNet/SC-InteractiveMap#161]
Rename Lake Forest area to Forest Lake, in English that phrasing flows better, minor thing of course not high priority.

**Comment by AnthorNet** [comment]
But isn't that the "official" name?

**Comment by ehoffman2** [comment]
The official name is "Lake Forest", as in the "forest with the big lake".  Similar to the dune forest, the northern forest, etc.

The area displayed is the biome, which in this case is a forest (officially denoted by the one with the big lake, hence the name of that biome).

**Comment by THECorranHorn** [comment]
labeling it Forest Lake would be much more specific and accurate with a map that has more than one lake

**Comment by ehoffman2** [comment]
I think the best course of action and most consistent way of doing it is to follow the official biome names as defined by Coffee Stain Studios.

Yes, indeed there are multiple forests with lakes in them, but I think that CSS reasoning for calling that forest the "lake forest" (and giving that name to the biome) was the importance that this lake give to the landscape of that biome.  In other word, that forest is recognized by it's huge lake.

It's the same reasoning behind the "dune desert".  Other deserts in this game have dunes too.

It's just that this forest is named after it's most prominent characteristic.

Regards,
Eric
