### ISSUE TITLE
[Feature Request] Visualize foliage removal and add a way to restore it.

### ISSUE THREAD

**Issue by IO5** [AnthorNet/SC-InteractiveMap#164]
The game stores removed foliage basically as a list of xyz entries. Editing them without a visual save editor is really impractical hence the request. The visualisation can be as basic as it gets e.g. a dot per entry and the only interaction needed in the app would be selecting and deleting them.

**Comment by AnthorNet** [comment]
It is not possible to show all foliages as they are stored only after deletion.
Now you can restore them by selecting an area already.
