### ISSUE TITLE
Using the height slider locks-out the ability to scroll the map.

### ISSUE THREAD

**Issue by CTXC** [AnthorNet/SC-InteractiveMap#169]
Unless I am missing some button to restore "Map scrolling", then the map height slider on the right side is causing the inability to scroll the map in a chrome browser.

100% repeatable, for me.

Adjust the height of the lower layer-view slider, found on the right side of the map, at the bottom. Now attempt to scroll the map, and all ability to scroll is disabled. (Both with the normal click-drag option and with the mouse's built-in "scroll screen", which uses the middle mouse button, on most mice, to bring-up a page-scroll tool.)

However, zooming in and out still functions. (I do not recall if the zoom "centers" under the mouse, which can be used, in a way, to navigate the map by zooming out and then zooming in on the mouse position.)

At some positions on the slider, the map will restore scrolling. I adjust the bottom slider to 0 elevation, the map does not scroll. I then adjust the top slider to 253 and now it can scroll. Now adjust the top slider to 100 and it stops scrolling... Again to 50, and now it works. Back up to 100 again, and it suddenly works. Back up to 253 and it may or may not stop working again.

If I had to assume, the "mouse" is somehow not "releasing focus" for "drag-drop", or "click-drag", after it is used within the slider. But, since the zoom does not need focus, or the focus is global for zooming, that simply transfers those actions through to the map, as the slider has no "zoom" ability, but it does have "drag-drop" or "click-drag" actions.

**Comment by AnthorNet** [comment]
Yes you're right :)
It happens when you release the mouse outside the slider, I'm still not sure how to fix it, may be by adding some timeout for when the slider don't move for a while.

I was waiting for complains do I'll have to fix it :D
