### ISSUE TITLE
Game version or build selection or limits

### ISSUE THREAD

**Issue by CTXC** [AnthorNet/SC-InteractiveMap#170]
Various versions have specific things available or unavailable. For instance, the tiers rewards, hard-drive recipes, shop items and research rewards. (For instance, in the MAM, I still see "flowers", which are no longer in the MAM, in the last few versions. As well as 2x "more pockets", in the caterium chain, which now only has 1x "more pockets". I do not recall the recipes, but I think something along the aluminum production chain was incorrect.)

However, the interactive map shows many items that are not available, which can be "edited", so they are added to the save-games. This is also in addition to crafting calculations, which don't always seem to be correct.

If you "detect" specific versions within the "loaded save file", or have a selection box to allow a user to set the version they are using... You could indicate a possible issue with "saving files", related to versions. You could also simply remove or add things and values which have been changed, in various versions. (This can be simplified by simply creating another database to check if XXX is within a specific version, and what the values are, for that version-range.) You would assume a new version has the same data as the last version, but warn of version indifference potential incompatibility. You should also be able to force constraints to a minimum version too. (Not everyone auto-updates games, so people may be a few versions behind, for various, reasonable reasons. Normally because many updates can break some mods or cause more issues than they tried to fix.)

**Comment by AnthorNet** [comment]
Removed the flower petals, even if technically they arer still hidden in the game :p
For the rest I can't support older version, mostly because even the save format have changed internally.

**Comment by AnthorNet** [comment]
Forgot to say Exp is supported when needed with a game version selector.
