### ISSUE TITLE
Western Dune Forest biome too wide

### ISSUE THREAD

**Issue by ehoffman2** [AnthorNet/SC-InteractiveMap#173]
The Western Dune Forest should only exists west of the larger map hole.  Currently the map shows this biome extending all the way to the Abyss Cliff, encroaching on most of the Eastern Dune Forest.

**Comment by AnthorNet** [comment]
It's working based on a global grid so not sure it's an easy fix right now :)

**Comment by AnthorNet** [comment]
See: https://static.wikia.nocookie.net/satisfactory_gamepedia_en/images/3/31/Biome_Map.jpg/revision/latest?cb=20210806163120

**Comment by ehoffman2** [comment]
This is the map I was referring to.  You can see on the map the extent of the Western and Eastern Dune Forest.  In the Web app, when hoovering over the map, a good portion of the Eastern Dune Forest is displayed as Western Dune Forest (instead of being similar to the image in the previous comment)..
