### ISSUE TITLE
Refactoring and Performance Improvements

### ISSUE THREAD

**Issue by RebeccaStevens** [AnthorNet/SC-InteractiveMap#176]
Hey @AnthorNet,

I've got quite a bit of free time on my hands at the moment and was wondering if you would be interested in me doing a bit of work on this project? I've got a few ideas on how to improve some of code behind the scenes.

I thought it would be best to discuss this with you beforehand though so that I know what I can and can't touch.

**Comment by AnthorNet** [comment]
Hey light be easier to come and discuss other Discord.
