### ISSUE TITLE
Site crashes when loading my save

### ISSUE THREAD

**Issue by Knowen** [AnthorNet/SC-InteractiveMap#178]
Hey,

when I try to load my current save file the site crashes during the step "parsing objects".
![image](https://user-images.githubusercontent.com/47173160/158052526-afc7b7ad-93df-4fd2-aed2-f3532aa13908.png)
save file:
[Thatsnewtome.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/8239233/Thatsnewtome.zip)

**Comment by AnthorNet** [comment]
Any mod used?

**Comment by Knowen** [comment]
Here is a list of all installed mods. Since the last time I used the interactive map, I haven't added any mod.

![image](https://user-images.githubusercontent.com/47173160/158054298-56e3b008-4eef-43cb-920f-f8035f42c0de.png)
![image](https://user-images.githubusercontent.com/47173160/158054317-0c8e4638-a326-4af7-a1bd-719ad82b4ddb.png)
