### ISSUE TITLE
Update Position +- buttons

### ISSUE THREAD

**Issue by SMERKIN5000** [AnthorNet/SC-InteractiveMap#18]
For the X/Y/Z fields it would be cool to have a +/- 4m button that autmatically adjusts the value in the field.

![image](https://user-images.githubusercontent.com/60308025/103595765-670fd180-4f50-11eb-9224-8796b29c9f41.png)

This would help a lot when:
* The number is a negative number and you want to do a negative offset - this always confuses me
* The number you are increasing jumps by the thousand digit and needs extra thinking

Now while a +/- 4m button for each field would be good, I think 3 buttons would be ideal. +/- 1m, +/- 4m, +/- 8m

**Comment by AnthorNet** [comment]
I agree on that one, it will require an extra step that may take some time!
The modal box used to handle forms is based on [BootBox](http://bootboxjs.com/) but that library wasn't handling multiple input, so it was rewritten for the most part.

- [ ] Migrate bootbox to custom script
- [ ] Migrate all previous bootbox
- [ ] Migrate modal to new scripts
- [ ] Add new custom input fields with buttons

**Comment by AnthorNet** [comment]
![image](https://user-images.githubusercontent.com/654353/103657453-39378680-4f6a-11eb-859e-8ad6126a3528.png)
