### ISSUE TITLE
Map Colour Settings export/import

### ISSUE THREAD

**Issue by catonthekbd** [AnthorNet/SC-InteractiveMap#19]
Would it be possible to export the colour map from a save file, so you could then re-import it into another save file?
(set up your prefered colours in one game, and then just re-use them in future ones)

**Comment by AnthorNet** [comment]
Like the idea, with a possibility to export/import color scheme and share them like the blueprints

**Comment by tophexbit** [comment]
I was looking for a way to sort the color preset list (alphabetically or custom order). Depending on the data format of the import/export feature sorting could be done without SCIM implementing such a feature. Seems like a "two birds with one stone" situation to me 🙂
