### ISSUE TITLE
Should `readString()` always return a string?

### ISSUE THREAD

**Issue by RebeccaStevens** [AnthorNet/SC-InteractiveMap#194]
Is this line supposed to return `undefined` or an empty string?

https://github.com/AnthorNet/SC-InteractiveMap/blob/e22a742a71f6185ce4ace0befff6a01f407fa6ca/src/SaveParser/Read.js#L1426

If `undefined` is intended, it should probably be made explicit to avoid confusion (i.e. `return undefined`).

**Comment by AnthorNet** [comment]
I don't even think it can come that far ;)
Error would be thrown before reaching that state

**Comment by RebeccaStevens** [comment]
In that case, let's just remove the return statement.
