### ISSUE TITLE
Can this dead code be removed?

### ISSUE THREAD

**Issue by RebeccaStevens** [AnthorNet/SC-InteractiveMap#195]
https://github.com/AnthorNet/SC-InteractiveMap/blob/e22a742a71f6185ce4ace0befff6a01f407fa6ca/src/SaveParser/Read.js#L127-L128

`window` isn't available in the worker context so even if the code wasn't dead, it wouldn't do anything.

**Comment by AnthorNet** [comment]
Yep.
Worker don't have any hide loader state, but to be fair, if the parsing is failing refreshing is as easy for the user.
