### ISSUE TITLE
Use Transformations Matrices

### ISSUE THREAD

**Issue by RebeccaStevens** [AnthorNet/SC-InteractiveMap#196]
Just thought I should write this down here rather than keeping it in the back of my head as "to do eventually".

Using [Transformations Matrices](https://en.wikipedia.org/wiki/Transformation_matrix) to store object positions and rotations will allow for much more powerful a flexible operations.

### Prerequisites

The codebase probably needs to undergo more refactoring to separate concerns so that these can easily be put in without causing a cascade of issues.

### Issues that will benefit from this

- #29
- #147

**Comment by AnthorNet** [comment]
No, UE don't use standard rotation and I don't intend to make it more complicated for me.
