### ISSUE TITLE
Circle - Other Block Types

### ISSUE THREAD

**Issue by dinoroger** [AnthorNet/SC-InteractiveMap#20]
Would be nice to be able to select the foundation thickness when making circles. Also pillar top selection as it may not show the clipping as bad.

**Comment by AnthorNet** [comment]
It generally takes the center foundation as type.
I'll add some small difference in height soon to avoid the clipping

**Comment by AnthorNet** [comment]
Closing as the foundation type used to spawn is the type being used.
