### ISSUE TITLE
[BUG] switch and light planel conection in blueprint

### ISSUE THREAD

**Issue by ShinoHarvest** [AnthorNet/SC-InteractiveMap#205]
if BP contain switch or light panel need delete cable connected and rebuild it to properly connected, this probaly not perfect copy of this item conector

**Comment by AnthorNet** [comment]
I guess this is the same as with the power circuits where we don't copy them and let the game rebuild :)

**Comment by AnthorNet** [comment]
Should be closed with 745cd0b0154b7c16a41124ce6eab880a3b606df2
