### ISSUE TITLE
Can't download file all of a sudden (5th of Match 2022)

### ISSUE THREAD

**Issue by AcidDayCat** [AnthorNet/SC-InteractiveMap#213]
Anyone else having problems today (5th of Match 2022) with file download in Interactive Map? Suddenly I can't download my file, been trying different saves, internet browsers etc. It just get stuck on "Compiling X collectables". What to do?

![56f24839855fabedb9cad53a79169641](https://user-images.githubusercontent.com/105000795/166955185-614caeed-f9e2-425b-b375-04120228afdb.png)

**Comment by AnthorNet** [comment]
Fixed soon, just the tile to get back at the office
