### ISSUE TITLE
Still no cables in copy pasted factories in dedicated server

### ISSUE THREAD

**Issue by GiBDargeth** [AnthorNet/SC-InteractiveMap#214]
Hi sorry to brag, the last issue i thought it was resolved resulted that I could import blueprints from the website into my server and worked ok by opening in single player first, saved then opening it in the server. 
The issue is when i lasso, copy paste factory somewhere else most of the cables are invisible even though I open it in single player (which is fine), save the session then launch the server with that save.

**Comment by AnthorNet** [comment]
I sadly cannot reproduce it myself, so my best bet is that you try to get the smallest save with reproducible steps.
