### ISSUE TITLE
Default to only showing resources within range of a Radar Tower

### ISSUE THREAD

**Issue by SignpostMarv** [AnthorNet/SC-InteractiveMap#216]
As mentioned [in today's YouTube video](https://youtube.com/clip/UgkxJnmVX3S3bs9IkJtFO072OngyOy6kFLxg), Radar Towers will now reveal Resource icons on the map.

In a similar fashion to the fog of war option on SCIM, it would be nice if uploading a save file would have the map default to only showing resources within range of a Radar Tower.

**Comment by SignpostMarv** [comment]
@AnthorNet fyi: Not sure if you can detect the game version from the save file, but if you plan on implementing this feature, it may be prudent not to enable this default behaviour for save games for older saves (because people playing the EA branch while Update 6 is in Experimental will not see this change reflected in the game, and it may be confusing for them when using SCIM)

**Comment by AnthorNet** [comment]
> @AnthorNet fyi: Not sure if you can detect the game version from the save file, but if you plan on implementing this feature, it may be prudent not to enable this default behaviour for save games for older saves (because people playing the EA branch while Update 6 is in Experimental will not see this change reflected in the game, and it may be confusing for them when using SCIM)

Yeah we got save version, build number and other stuff ;)

**Comment by AnthorNet** [comment]
It could even be done by just using the fog of war

**Comment by SignpostMarv** [comment]
@AnthorNet intent of this feature request is to mimic the behaviour of the Update 6 map, so if it shows up resources you've walked past but not radar towered, that'd be good 👍
