### ISSUE TITLE
Fill multiple inventories with the same thing

### ISSUE THREAD

**Issue by meza** [AnthorNet/SC-InteractiveMap#22]
Sometimes you just need a large amount of containers full of something.
Currently the only way of doing it is to "right click -> click fill -> select item -> click ok" for each inventory.

It would be nice to have an option to fill all inventories in the given selection with something.

In a similar vein, it could be nice to right click on a train and have a "fill train with..." option to fill every freight car with a single item.

**Comment by AnthorNet** [comment]
Need to check how fluid freight wagon are handled ^^

**Comment by meza** [comment]
Let's hope it's not too different to how solids are

**Comment by AnthorNet** [comment]
I don't have any save with them in hands, for testing? Can you get something? 📄

**Comment by meza** [comment]
There should be a few here somewhere. They are regular freight cars until they are filled with water though.
[Long Train.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/5838178/Long.Train.zip)

**Comment by AnthorNet** [comment]
We are getting there! Soon :p
