### ISSUE TITLE
Convert Markers & Stamps to Beacons

### ISSUE THREAD

**Issue by SignpostMarv** [AnthorNet/SC-InteractiveMap#222]
While Update 6 is in Experimental (and possibly after), button/checkbox to convert Markers & Stamps to Beacons may be useful to aid people hopping back and forth between game versions.

**Comment by AnthorNet** [comment]
Not possible to switch due to save format changes

**Comment by SignpostMarv** [comment]
@AnthorNet the save format changes would be kind of the point, given the idea was to support downgrading a save file to be update 5-compatible?

**Comment by AnthorNet** [comment]
It would require too much work to downgrade to the old format, mainly because all internal collectables and foliage have ganges pathnames
