### ISSUE TITLE
Can't fill storage with materials, just gas and liquids

### ISSUE THREAD

**Issue by wolfrumgaming** [AnthorNet/SC-InteractiveMap#227]
I recently used your interactive map, and I used to be able to fill it with any solid object in the game, but now I can only fill it with the liquids in game and the gases. Not sure what else to do.
![Screenshot (16)](https://user-images.githubusercontent.com/106153029/170010568-aa7351be-5b66-4a7f-bf3d-29c266f72a50.png)

**Comment by AnthorNet** [comment]
My bad ^^ Missed a part this morning :D
