### ISSUE TITLE
My save may be too big for the editor to open.  

### ISSUE THREAD

**Issue by BLAndrew575** [AnthorNet/SC-InteractiveMap#228]
Not exactly sure where this would fall topic wise as it doesn't appear to be a bug and its certainly not a feature request, but my save stopped loading in the save editor about 6 months ago.  Figured it was a one time thing and gave it some time.  I only really use it to get information from my save.  My save is currently the benchmark and is being used to optimize the game for update 6 by Coffee Stain because of its magnitude.   Loading it up in the save editor either causes it to never load any progress after about 1/3rd of the way or if it does load(After about 20 minutes), one click on nearly anything causes it to run out of memory.  As far as I can tell, its not my browser and I have tried several other browsers. I am happy to provide my save, just don't want it public just yet and not sure if posting it here will make it public. 
![Out of memory](https://user-images.githubusercontent.com/106648858/171337942-53dd0189-171b-442e-973c-41698c6bc561.JPEG)

**Comment by AnthorNet** [comment]
Hey send it to me on discord ;)

**Comment by Catafly** [comment]
I have the same issue. as soon as the browsers (chrome,Firefox) hit 6.5 GB memory usage I get out of memory exception.
After tweaking the cache setting in Firefox it dose load but as soon as I try to do anything I get the out of memory exception.
My save is nowhere near as big as BLAndrew575 only 27.9MB.

**Comment by THECorranHorn** [comment]
I suspect the only way of overcoming this is to setup cloud computing on the site to take the load off the local computer, could get pricey unfortunately

**Comment by AnthorNet** [comment]
That has nothing to do with cloud computing or else it is simply a current limitation on browser and the fact the save have too much object to be handled.

**Comment by Catafly** [comment]
Hi
I spoke to BLAndrew575 he said he can now load his save. I have tried to load mine using opera GX but still fails to load with the same out of memory error.
Are you able to assist with console commands or advice?

**Comment by AnthorNet** [comment]
Send your save please, I've managed to handle a 47mb save without any trouble using the last rewrite so the issue should now be closed.

**Comment by AnthorNet** [comment]
1be431c71ecfe800a3f6f25616d4c8dc0c04a93b / 27940f452231fb06d44f5b0e7d5849d7d0267aaa
