### ISSUE TITLE
displayed max. power consumption ignores overclocking

### ISSUE THREAD

**Issue by ThomasGP** [AnthorNet/SC-InteractiveMap#229]
# Issue
In the power circuits overview, the "Max. Cons." value seems to be the sum of the unadjusted power used of a production building. This was confusing for me, since I heavily rely on the "overclock miners / oil extractors, underclock production buildings" play style.

## Replication
1. load any savefile with over-/underclocked buildings
2. compare the displayed power consumption in SCIM with the ingame value (power graph or console "ShowDebug Circuits")

### Actual Result
there is a difference in the "maximum consumption" value for every power circuit that has these buildings in it. "Consumption", "Production" and "Capacity" values are not affected, of course.

### Expected Result
SCIM should use the configured clock speed like this:
- in Circuit.js (currently line 212 on the main branch), do not just use [buildingData.powerUsed](https://github.com/AnthorNet/SC-InteractiveMap/blob/main/src/SubSystem/Circuit.js#L212) for the current component to sum statistics.maxConsumption, instead:
  - for clock speed, use the "mCurrentPotential" property (if thats not available, use "mPendingPotential", defaulting to "1.0")
  - with that clock speed, calculate according to the [wiki formula for production buildings](https://satisfactory.fandom.com/wiki/Clock_speed#Clock_speed_for_production_buildings): clock speed to the power of 1.6, times the powerUsed

some side notes:
- I hope my textual proposal for the Circuit.js change above is clear, I take it that you do not want forking / creating a pull request for this project
- I did not look into shortcomings / bugs for overclocked power generators (which would affect the Production/Capacity values), since that is not part of my play style
- maybe this is a thing for an Update 6 release, given the [proposed change](https://www.reddit.com/r/SatisfactoryGame/comments/v37f7g/changes_to_power/iax435k/) to linear overclocking

**Comment by AnthorNet** [comment]
Thank you, fixed internally and should be released with Update 6
