### ISSUE TITLE
Saving a savegame causes the browser to crash

### ISSUE THREAD

**Issue by sickneur** [AnthorNet/SC-InteractiveMap#232]
Since yesterday I've tried to modify my savegame in the interactive map, it does load and i can work with it, but when I try to save it, it starts to save and at some point in the process the browser shows an error page.

I've tried in the Early access branch with an Early Access U5 savegame, in Chrome, Edge and Opera with the same result, i've also tried with an old savegame from U5 that I could load and modify on late May this year, and it crashes while saving.

I've also tried with a savegame from U6 in the experimental branch, and also crashes.

**Comment by AnthorNet** [comment]
You'll need to send your save!
But it could be related to 27940f452231fb06d44f5b0e7d5849d7d0267aaa
