### ISSUE TITLE
Old blueprints broken

### ISSUE THREAD

**Issue by SquirtuS** [AnthorNet/SC-InteractiveMap#234]
# Issue
Starts from today, any save file create in calculator with inserted blueprint have infinity load issue in game, or crash.
If i create save file with no changes it will work fine.

Crush report
Version: 188609, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Standalone, IsUsingMods: Yes

Assertion failed: Tag.Size == Loaded [File:D:/ws/SB-lowprio/UE4/Engine/Source/Runtime/CoreUObject/Private/UObject/Class.cpp] [Line: 1497]

FactoryGame_Core_Win64_Shipping!AssertFailedImplV() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:104]
FactoryGame_Core_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Private\Misc\AssertionMacros.cpp:461]
FactoryGame_CoreUObject_Win64_Shipping!UStruct::SerializeVersionedTaggedProperties() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:1497]
FactoryGame_CoreUObject_Win64_Shipping!UStruct::SerializeTaggedProperties() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:1285]
FactoryGame_CoreUObject_Win64_Shipping!UScriptStruct::SerializeItem() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:2777]
FactoryGame_CoreUObject_Win64_Shipping!FStructProperty::SerializeItem() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\PropertyStruct.cpp:153]
FactoryGame_CoreUObject_Win64_Shipping!FPropertyTag::SerializeTaggedProperty() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\PropertyTag.cpp:242]
FactoryGame_CoreUObject_Win64_Shipping!UStruct::SerializeVersionedTaggedProperties() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:1476]
FactoryGame_CoreUObject_Win64_Shipping!UStruct::SerializeTaggedProperties() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:1285]
FactoryGame_CoreUObject_Win64_Shipping!UObject::SerializeScriptProperties() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Obj.cpp:1457]
FactoryGame_CoreUObject_Win64_Shipping!UObject::Serialize() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Obj.cpp:1399]
FactoryGame_CoreUObject_Win64_Shipping!UObject::Serialize() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Obj.cpp:1262]
FactoryGame_Engine_Win64_Shipping!AActor::Serialize() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:781]
FactoryGame_FactoryGame_Win64_Shipping!FArchiveObjectDataProxy::operator<<() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGSaveSession.cpp:1526]
FactoryGame_FactoryGame_Win64_Shipping!operator<<() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Core\Public\Containers\Array.h:1176]
FactoryGame_FactoryGame_Win64_Shipping!UFGSaveSession::SerializeLoadedObjects() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGSaveSession.cpp:1747]
FactoryGame_FactoryGame_Win64_Shipping!UFGSaveSession::LoadCompressedFileFromDisk() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGSaveSession.cpp:957]
FactoryGame_FactoryGame_Win64_Shipping!UFGSaveSession::LoadGame() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGSaveSession.cpp:1102]
FactoryGame_FactoryGame_Win64_Shipping!AFGGameMode::InitGameState() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameMode.cpp:266]
FactoryGame_Engine_Win64_Shipping!AGameModeBase::PreInitializeComponents() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\GameModeBase.cpp:125]
FactoryGame_Engine_Win64_Shipping!ULevel::RouteActorInitialize() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\Level.cpp:2001]
FactoryGame_Engine_Win64_Shipping!UWorld::InitializeActorsForPlay() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\World.cpp:4365]
FactoryGame_Engine_Win64_Shipping!UEngine::LoadMap() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:13220]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::LoadMap() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:32]
FactoryGame_Engine_Win64_Shipping!UEngine::Browse() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12465]
FactoryGame_Engine_Win64_Shipping!UEngine::TickWorldTravel() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\UnrealEngine.cpp:12663]
FactoryGame_Engine_Win64_Shipping!UGameEngine::Tick() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Engine\Private\GameEngine.cpp:1794]
FactoryGame_FactoryGame_Win64_Shipping!UFGGameEngine::Tick() [D:\ws\SB-lowprio\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGGameEngine.cpp:16]
FactoryGame_Win64_Shipping!FEngineLoop::Tick() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:4896]
FactoryGame_Win64_Shipping!GuardedMain() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\Launch.cpp:169]
FactoryGame_Win64_Shipping!GuardedMainWrapper() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:137]
FactoryGame_Win64_Shipping!WinMain() [D:\ws\SB-lowprio\UE4\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:268]
FactoryGame_Win64_Shipping!__scrt_common_main_seh() [d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by AnthorNet** [comment]
Agree. I messed up something in the format conversion.

I've deployed a quick fix when saving but further details needs to be handled tomorrow.
