### ISSUE TITLE
Add download button when using savefile download URL

### ISSUE THREAD

**Issue by Rosuav** [AnthorNet/SC-InteractiveMap#237]
When you open the interactive map using an automatic load URL eg https://satisfactory-calculator.com/en/interactive-map?url=https://gameserver.example/fetchsave the download button is not present. It continues to be absent even if you manually load a save.

Would be very helpful to be able to download the save file in this way. It might be necessary to guess at a file name (since there won't necessarily be one from the server), but even if it always just called it "Untitled Save File.sav" or something, it would be extremely helpful.

**Comment by AnthorNet** [comment]
Fixed

**Comment by Rosuav** [comment]
Thanks!
