### ISSUE TITLE
Absolute direction mass rotate.

### ISSUE THREAD

**Issue by kajahama** [AnthorNet/SC-InteractiveMap#238]
I would like to have feature where you can mass rotate selected items to specific absolute rotation angle.  
Currently mass selection rotate only allows for offset rotation from current value.

Currently you can do this for single item with the right-click Update position -feature.

Would it be possible to get similar absolute rotation functionality to mass select, Positioning category?
Separate from current relative rotation already in there.

My main use would be so I could turn all selected foundations to exactly same direction, instead of mix of four different facings.

**Comment by kajahama** [comment]
Meant rotate in place to specified absolute rotation value for each item in selection.
And I acknowledging it will create a real mess if done with something other than flat foundations and similar.

**Comment by AnthorNet** [comment]
Wasn't sure but I get your point ;)

**Comment by TheAndr0id** [comment]
This would allow a map to be "repaired" and remove the rotation bug found here:
https://questions.satisfactorygame.com/post/5fa0f8ad6077ad3d714c899c

The TL;DR: is foundations with an angle of 315 degrees are currently bugged and buildings will not rotate to all 4 angles (I'm guessing 315 + 90 > 360 = MATH IS HARD).  Being able to set all the foundations to anything less than 315 works.

**Comment by kajahama** [comment]
I have been thinking about trying to whip this together from code in src/Modal/Object/Position.js and src/Selection/ since filing the original feature request, but I just haven't had time and energy to get necessary testing environment up (if even possible when repository isn't meant for copying wholesale) and then understanding the current code enough to try.

I think this would "only" need a new option to selection menu, with limited form asking just for "Rotation (Angle between 0 and 360 degrees)" without prefilled value (copying from Position.js?).
And functional code that starts as fork from Selection/Offset.js or Selection/Rotate.js to run the code used for single object right click "Update Position" on each of the objects in the selection.

**Comment by AnthorNet** [comment]
It will be added after update 6

**Comment by TheAndr0id** [comment]
> This would allow a map to be "repaired" and remove the rotation bug found here: https://questions.satisfactorygame.com/post/5fa0f8ad6077ad3d714c899c
> 
> The TL;DR: is foundations with an angle of 315 degrees are currently bugged and buildings will not rotate to all 4 angles (I'm guessing 315 + 90 > 360 = MATH IS HARD). Being able to set all the foundations to anything less than 315 works.

After doing some digging into this bug, it only causes the issue for foundations EXACTLY at 315 degrees.  I rotated my entire base by 0.1 degree and the problem went away.  This actually works out better since it's near impossible to control the angle of connected foundations (it is determined by the angle of the piece connected to the new foundation and what side you connect to... aka random.  Zooping causes another whole headache.)  

This solution means I don't have to keep coming back to rotate the foundations on mass to 45 degrees.  Everything is at 45.1 degrees (and the variants of) and thus I'm no longer in need of this functionality.

It might still be a nice thing to have, but I wouldn't use it at this point.

**Comment by matthock** [comment]
I'll add another vote for it even if OP is less interested. Main interest is fixing randomly-aligned foundations that are on the world grid but have different facings. A feature to mass select foundations by some criteria (such as some combination of on a particular/the world grid, at a particular alignment and/or one of its other three cardinals, and region bounding) and then force them to be consistent would, while not per se *useful*, potentially relieve much OCD!

**Comment by TheAndr0id** [comment]
> > This would allow a map to be "repaired" and remove the rotation bug found here: https://questions.satisfactorygame.com/post/5fa0f8ad6077ad3d714c899c
> > The TL;DR: is foundations with an angle of 315 degrees are currently bugged and buildings will not rotate to all 4 angles (I'm guessing 315 + 90 > 360 = MATH IS HARD). Being able to set all the foundations to anything less than 315 works.
> 

And just a follow up, this bug has been addressed in Update 6, so it's no longer an issue.  I used the current rotate feature to remove the 0.1 degree increment I did before and building on any foundation works fine.  There's some mention in the newly released Update 7 about foundation alignment, so maybe some of these issues can be dealt with, I don't know, maybe, if the stars align, by fixing the issues themselves in the game...

I'm just sayin'   :-P
