### ISSUE TITLE
Bug, Update 6, Pipe flow indicators don't move right when offsetting pipes.

### ISSUE THREAD

**Issue by kajahama** [AnthorNet/SC-InteractiveMap#239]
# Issue
In Update 6:
When mass offsetting pipes, flow indicators move in different direction than the pipe itself, leading to flow indicators hanging in air.

## Replication
Build pipe in game and save.
Offset pipes in the editor.
Open save in game.

### Actual Result
Flow indicators have moved in some direction relative to the pipe by the amount of offsetting done.
For example when I moved factory 12m up, pipe flow indicators were now at right height, but off from normal position in some direction.
Indicators will be oriented east-west if not along a pipe.

Position doesn't get fixed by itself with time.
Position doesn't get fixed by saving and loading.
Position doesn't get fixed by recoloring the pipe.

Position gets fixed by changing pipe type.

### Expected Result
Flow indicators move with their pipes and relative positioning between indicator and pipe doesn't change.

### Partial cause
Update 6 has pipe flow indicators as separate property for the pipe, which isn't case with Update 5.
This new child object has "needTransform" set to true and separate rotation and translation values.
This has probably been done as preparation for having pipe types without flow indicators.

**Comment by AnthorNet** [comment]
Hmm I did not manage to reproduce that behavior

**Comment by AnthorNet** [comment]
![image](https://user-images.githubusercontent.com/654353/175021225-683078f6-cd92-402d-b5b3-6799a8c0aec8.png)

**Comment by kajahama** [comment]
Ok.

I'll test more.

Might also be that it was fixed in some late update you have done.

Has been couple of days since I last moved anything with pipes.
But had it on three separate offsets back then.

And those were old pipes that were laid in Update 5.

**Comment by kajahama** [comment]
So my bad with the replication section, will update to actual if I can still replicate.

**Comment by AnthorNet** [comment]
`And those were old pipes that were laid in Update 5.`

That might be it, possibly those old one aren't linked properly in the save with the flowIndicator, can I get the save to check?

**Comment by kajahama** [comment]
![Screenshot20220622-15032600000](https://user-images.githubusercontent.com/13135393/175024922-9261a91e-2851-4bb4-9681-b6b2c8c6870c.png)

Seems there is one specific orientationt that works, and you probably hit just it.

One of each pair is done in opposite direction.
Except I probably made mistake with the upright ones.

Moved 8m west, 8m south and 8m down.

Camera direction is SSW.

**Comment by AnthorNet** [comment]
I see, pipes use splineData thus are always angled at 0°.
Need to use this special case.
