### ISSUE TITLE
Packager outline is oversized

### ISSUE THREAD

**Issue by noe-caratini** [AnthorNet/SC-InteractiveMap#24]
The size of the Packager on the map doesn't reflect its actual size (should be ~1 foundation)

![image](https://user-images.githubusercontent.com/31419954/104988124-2d8a9c00-5a0f-11eb-981b-ef9108a6a310.png)

**Comment by AnthorNet** [comment]
Changed it to 8x8x12 meters!

See: https://satisfactory-calculator.com/en/buildings/detail/id/Build_Packager_C/name/Packager

Should be ok?
