### ISSUE TITLE
All mobs except Flying Crab Hatchers are gone again. No mods

### ISSUE THREAD

**Issue by Shedar-1** [AnthorNet/SC-InteractiveMap#245]
# Issue
All mobs except Flying Crab Hatchers are gone again. No mods. Latest Exp branch

## Replication
1. I increased inventory space for my character (300 slots total)
2.  I started New Year event once setting system date to 01/01/2022 may be this could cause the bug?

### Actual Result
There crabs only in the world

### Expected Result
New Year event and more inventory slots

**Comment by Shedar-1** [comment]
https://disk.yandex.ru/d/Q2uY-pNEHgf_Cg
save file

**Comment by AnthorNet** [comment]
Don't think it's related to the map :)
