### ISSUE TITLE
Sign with number layout do not render correctly

### ISSUE THREAD

**Issue by KreizIT** [AnthorNet/SC-InteractiveMap#247]
# Issue
Sign (at least 0,5x0,5, not tested with other) do not render number in SCIM correctly. By the way, update text in SCIM do not affect sign in game.

## Replication
1. In game, set sign to number layout and set number
2. Load in SCIM, display default value "10"
3. Update text in SCIM
4. In game, number is still original one.

### Actual Result
Sign text value is not in sync with ingame.
![InGame SIgn](https://user-images.githubusercontent.com/3184387/183943535-ffaf72ef-a29a-4acb-9526-cfc34aa652aa.jpg)
![SCIM Sign](https://user-images.githubusercontent.com/3184387/183943672-a51bb63b-3105-4276-abc2-4a72ab6f26aa.jpg)

### Expected Result
View in game value in SCIM and SCIM updated value in game.

**Comment by AnthorNet** [comment]
It was apparently changed in U6. I'll have to check all the implications.

**Comment by AnthorNet** [comment]
I believe it's ok for U6, not sure about U5, but should not be longer before it's gone.

**Comment by KreizIT** [comment]
I checked. Display in SCIM is ok for U5. I haven't tested update number.
Thanks you.
