### ISSUE TITLE
Creatures issue after edited save file in interactive-map

### ISSUE THREAD

**Issue by KOZAKASHII** [AnthorNet/SC-InteractiveMap#248]
# Issue
All creatures instead Flying Crab Hatcher are not respawning anymore, and also tamed Lizard Doggo not generating items

## Replication
When playing save file which was edited in interactive-map(Experimental Update 6, no Mod)

**Comment by AnthorNet** [comment]
Related to #245 
Still unsure it is related to the map as we do not touch the creature spawner.

**Comment by AnthorNet** [comment]
Could you upload your save?

**Comment by KOZAKASHII** [comment]
[exp220822.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/9394125/exp220822.zip)

**Comment by KOZAKASHII** [comment]
[exp220822.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/9394139/exp220822.zip)

**Comment by AnthorNet** [comment]
You can't really get the spawner to spawn anything with that amount of power you have every where on the map ;)

**Comment by KOZAKASHII** [comment]
But before I edited my save file on interactive-map everything seems to be fine, and still it didn't explain the Lizard Doggo problem though.
Maybe after the Update 6 official release all thing will be fix.
