### ISSUE TITLE
Fog of War hiding explored territory

### ISSUE THREAD

**Issue by jlellis** [AnthorNet/SC-InteractiveMap#249]
I've built a train line north from the rocky desert, at sea level to the world border.  Most of that new rail line is still being blocked by the Fog of War.    If I disable Fog of War, my stuff is visible.  I've tried reloading the map, and reloading the page in the browser, but the Fog of War persists.

Screenshot attached.   
![Fog of War Issue](https://user-images.githubusercontent.com/49498950/187050337-c613c6b6-9238-42cf-ab69-49da6fc33248.PNG)

**Comment by AnthorNet** [comment]
Hey,
How is your FOW in game?

If not the same, please link your save.

**Comment by jlellis** [comment]
I didn't ever notice the game has a FOW for the player.  As far as I'm aware, its all normal.  It's not extra dark or foggy out there, though I did notice one visual glitch when I stood on a rail line vs on the foundation under it... the sky looked like it turned to a night-time lighting.  I'll attach the save here.

**Comment by jlellis** [comment]
[Gyles19 Two EA4.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/9438962/Gyles19.Two.EA4.zip)

**Comment by AnthorNet** [comment]
![image](https://user-images.githubusercontent.com/654353/187865579-186b4303-c3aa-40ee-89b6-abdf9deaa544.png)

Looks coherent with game for me. Also updated last height map data from update 6.
