### ISSUE TITLE
Production from supported mod machines not calculated in statistics modal

### ISSUE THREAD

**Issue by noe-caratini** [AnthorNet/SC-InteractiveMap#25]
Not sure if this is an SCIM issue or if it's up to the mod author here.

When using the Mk++ mod ([https://ficsit.app/mod/4HFJNS71Ua5TrR](url)), production from some of the mod's machines is not taken into account in the statistics tab.

More specifically it looks like SCIM doesn't have data on machines above Mk2 (possibly outdated data?)

![image](https://user-images.githubusercontent.com/31419954/105046253-c5fd3c80-5a60-11eb-8ba8-7e3833d0edd0.png)

![image](https://user-images.githubusercontent.com/31419954/105046226-bda50180-5a60-11eb-944a-859816bcc9d9.png)

**Comment by AnthorNet** [comment]
I believe it's because the mod buildings weren't put in production category by the mod author.
I did it for the Refinery MK4, could you confirm if it changed a thing or not?

**Comment by noe-caratini** [comment]
Looking good for the Refinery !

![image](https://user-images.githubusercontent.com/31419954/105047046-c34f1700-5a61-11eb-9347-65a8012ca5ae.png)

**Comment by AnthorNet** [comment]
It is just the mod that is not complete in our backend then :)

**Comment by noe-caratini** [comment]
Is it something you can fix or is it up to the mod author ?
Or is there a way to contribute somehow by providing buildings data ?

**Comment by AnthorNet** [comment]
It's normally to the mod author to finish the implementation.
I tried to add all the buildings to the production category, but all recipes and consumptions, sizes, needs to be added by the mod author as I don't know them :)

**Comment by AnthorNet** [comment]
As it's not related to the map code, I'm gonna close this one :)
