### ISSUE TITLE
Statistics on map menu do not update when map is updated multiple times

### ISSUE THREAD

**Issue by gyles19** [AnthorNet/SC-InteractiveMap#250]
# Issue
Statistics on the map menu menu seem to reflect only the first map loaded into the browser.  Uploading newer maps with new production does not update the statistics in the main menu. Manually selecting  the entire map does compute the statistics properly.

## Replication
1. Upload a map file
2. use the map menu Statistics to look at an item, say Stators.
3. In game, add machines to craft more Stators.
4. Wait for an autosave, then upload the latest save file.
5. Use the map menu Statistics to look at the item again.  The production number does not change.
6. Zoom out, select the entire map manually with the rectangle tool, view production statistics, the number for the item is correct.
7. Reload the Interactive Map tool by browser's "reload this page"
8. Upload the same latest save file again
9. use the map menu Statistics to look at Stators.  The production number is now correct.

### Actual Result
Statistics do not refresh when a new map is uploaded

### Expected Result
Statistics should reflect values on newest uploaded map, not the first map uploaded.

**Comment by AnthorNet** [comment]
Tested it and the statistics modal is refreshed every time the modal is open.
Not sure I'm able to reproduce what you say.

**Comment by AnthorNet** [comment]
Closed too soon :D
