### ISSUE TITLE
Edit vehicle inventory

### ISSUE THREAD

**Issue by RenaKunisaki** [AnthorNet/SC-InteractiveMap#252]
Unless I'm missing something, it doesn't seem to be possible to edit a vehicle's inventory.

Of course you can edit the player/storage container inventory and just move it to the vehicle in-game, but I was hoping to put a stack of 9999 in the fuel slot, and the excess just disappears (ie it becomes a stack of 100) if I do it that way. (I didn't want to just enable the No Fuel Cost option because I don't know if that affects generators too?)

**Comment by AnthorNet** [comment]
I need to check for the fuel part ;)

**Comment by AnthorNet** [comment]
Not sure you can by pass the max stack as the game would rewrite it after the first consumption.
