### ISSUE TITLE
Add Update 6 new collectibles

### ISSUE THREAD

**Issue by Vectorspace000** [AnthorNet/SC-InteractiveMap#254]
Update 6 has landed in Early Access and adds new collectibles that were not in Experimental (tapes for the boombox, maybe more?)

They could be added to the Interactive Map.

**Comment by AnthorNet** [comment]
They are in the awesome shop unlocks and the last one are in the special tabs

**Comment by Vectorspace000** [comment]
@AnthorNet there are some that are not in thr shop, that are out in the map instead. E.g. the deep rock galactic tape is in the cave behind the waterfall, near the 5 coal nodes north of grass fields, and is not in the shop

**Comment by AnthorNet** [comment]
As I said the one not in the awesome shop are in the special tabs under research.

**Comment by Vectorspace000** [comment]
@AnthorNet What do you mean "special tabs under research"

**Comment by AnthorNet** [comment]
![image](https://user-images.githubusercontent.com/654353/191318879-80953e29-dab8-4255-8306-67d0bade58b2.png)

**Comment by RubyRezal** [comment]
That's fine for people who just want to edit their save and unlock them... but that really doesn't help those of us who would like a map marker to help us find the tape locations through normal play.  It would be nice to have map markers for the tapes as an option as well.
