### ISSUE TITLE
How to copy inventory items form guest to host player?

### ISSUE THREAD

**Issue by ZaxonXP** [AnthorNet/SC-InteractiveMap#255]
I have a backup of the game moved to the new installation and now I cannot load it (probably different session name). When I create new game and save the state, I copied the backup to newly created folder. Now I can load the old save game state, but the player respawn at the base and not in the last location. If I go to that location I see the offline player sitting and drinking coffee. 

When I upload the save I see in the options that there is one Guest and one Host player, but no way to copy the inventory from guest to host. Will it be possible to do this in the future?

What will happen if I delete guest player? Will the inventory items be gone or stored somewhere?

I only play single player.

Kind regards,
Piotr

**Comment by AnthorNet** [comment]
Not possible to copy it but you can kick the yoga engineer to death to get it's inventory back in game.

**Comment by ZaxonXP** [comment]
@AnthorNet : I did not know that is possible. Thanks for the tip. Yoga went to abyss and the items to the right owner. :)
