### ISSUE TITLE
Feature Request: Add option to undo after deleting

### ISSUE THREAD

**Issue by Cyrillic1** [AnthorNet/SC-InteractiveMap#256]
Other actions such as rotating or moving buildings give you an option to undo them, but deleting does not give you such an option

PS: i just lost about an hour of work because i could not undo an accidental deletion of 7000+ items :)

**Comment by AnthorNet** [comment]
Cannot make any promises on that one as undo are very complicated, and you also need to keep all objects and connection in memory.
