### ISSUE TITLE
Small Frame Pillars are not rendered with diagonal rotation

### ISSUE THREAD

**Issue by ehoffman2** [AnthorNet/SC-InteractiveMap#258]
# Issue
I have belts with Small Frame Pillars (steel frames) around them, you know, to make it "look nice"!  However, I have some stretches where the belt is running diagonally (45 degree).

The belts are displayed fine in SCIM, but each frames are displayed oriented cardinally, east-west, instead of being shown properly oriented.

## Replication
Place small frame pillars diagonally aligned (NE-SW for example).  Load the save in SCIM.  Look at the pillars render overlay.

### Actual Result
Each pillars are displayed as a discontinuous aggregation of East-West aligned rectangles

```
 ___
|___|
     ___
    |___|
         ___
        |___|
             ___
            |___|
```

### Expected Result
Each pillars are displayed continuously with the same orientation as in the save file.

```
  /\
  \ \
   \/\
    \ \
     \/\
      \ \
       \/\
        \ \
         \/

```

**Comment by puttehi** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/19575408/4d5b5f99-cc0d-4366-8c9e-d6c128d40714)

Example image with green lines showing expected orientation
