### ISSUE TITLE
Copy / Paste Bug: objects offset and rotated

### ISSUE THREAD

**Issue by slendererer** [AnthorNet/SC-InteractiveMap#259]
# Issue
When copy & pasting, the pasted objects are offset a few meters north(Y axis) and rotated 90 degrees clockwise. 

## Replication
1 select objects
2 copy
3 paste on true center foundation, with only positive Z axis offset

### Actual Result
pasted objects are offset multiple meters north (y axis) and rotated 90 degrees clockwise. 

### Expected Result
Copy Pasting should paste exactly centered on/over the pasted object, and be not rotated.

**Comment by slendererer** [comment]
Github seems to be having issues, i cannot upload images or a video demonstrating this issue. If you want screenshots or a video of the issue, hit me up on Discord, I am already in the EDSM server @miles_smiles #4526

**Comment by AnthorNet** [comment]
Are you sure the pasting foundation is at a rotation of zero degrees?

**Comment by AndNovAtor** [comment]
@AnthorNet is very correct, I also forgot some simillar problem, thx.

Don't know, but I want to show what I forgot.

I creted some "road". Sic, it was important HOW I created road (and yes, I "played" with "fill" and rotate)
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3628514/039b3de6-0808-40ca-9ae8-b2c9895200f7)

And I created test 1 rail road
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3628514/7a8655b6-a126-4cb0-8267-548f76be6f25)

So. I copy this "test" road.

Then, If I simply [right mouse] cliced on "foundation" with the road place from first image, clicked "Paste 1 item", then I got this:
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3628514/6f6571a0-2622-4d8e-b277-91ca7a9fcad5)

But it's "corect"! Again, it cause HOW I created a "road". And cause that - "foundation", that I clicked, is rotated.
This is "cause".

So. I can bulk rotate a road section ~(btw, I suddenly saw, that it was even 89.999999 degree for one and 180.002 degree for another, not 90 or 0; my bad, huh)~.
Or for one "hit", I can simply rotate a one "foundation". Like this, "rotate by 90 degree":
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3628514/755d2f70-ae52-4a15-8010-03982b4c03f2)

And even if after that "foundation" again had "wrong" oriantation, when I pasted rail - I got "horizontal" orientation:
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3628514/146a5dfa-581f-463d-9e1b-84df01c54053)

So again, @slendererer, please check "foundation" current rotation, on which you paste items (for example, through "Update position")

~P.s. - I misinterpretaded issue date, so kind of necroposting, sorry~

**Comment by AnthorNet** [comment]
As it's old, I'll close it :) Thanks for the great explanation, it might help other users.
