### ISSUE TITLE
Remember unselected layers

### ISSUE THREAD

**Issue by Arno989** [AnthorNet/SC-InteractiveMap#266]
When loading my save I need to wait until the rendering is complete to unselect the things I don't want rendered for performance and "readability".
The render state of the slugs, disks and other non-user related layers are remembered in the cookies but player related layers aren't.
If this would be the case it would have more efficient loading times since unselected items don't need to be rendered and I don't have to unselect them every time I update the save during play.

Example of how I like to view my map:
![image](https://user-images.githubusercontent.com/32594687/196451794-dc363c8e-bd4b-40fc-82a1-cedd7eb7655a.png)

I think this would be fairly easy to save in cookies or account data

**Comment by AnthorNet** [comment]
As a starter the map options can be updated to not shown structures by default

**Comment by Arno989** [comment]
yes, but player info cannot be configured, this would be a good compromise on my issue imo
