### ISSUE TITLE
Missing gas pillars

### ISSUE THREAD

**Issue by kajahama** [AnthorNet/SC-InteractiveMap#267]
Gas pillars are missing from the map at following coordinates:
Field as triangle from about -118,036 / -160,541 to -108,721 / -153,584 to -108,882 / -165,632

**Comment by kajahama** [comment]
Also gas pillars under drop pod at 90,000 / -150,000 have been removed from the game with Spire Coast / Great Canyon update.

**Comment by kajahama** [comment]
Also: Gas pillars around Sulfur node at 126,724 / -46,636 are missing.

**Comment by kajahama** [comment]
Also: Gas pillars inside tunnel at -128,300 / -93,000 are missing.

**Comment by kajahama** [comment]
Also: Gas pillars around Yellow Power Slug at -176,529 / -69,673 are missing.

**Comment by kajahama** [comment]
Also: Gas pillars around Purple Power Slug at -218,427 / 24,200 are missing.

**Comment by kajahama** [comment]
Also: Gas pillars around Yellow Power slug at -169,712 / 206 are missing.

**Comment by AnthorNet** [comment]
Gaz pillars are manually sourced with a mod, and you need to spawn everywhere which makes it hard.
I'll try to do another pass soon. But need to take a complete day for it.

**Comment by kajahama** [comment]
Yeah, I understood from the old similar bug report.

Exploring the map currently for drop pods on a new save and started compiling a list of places I noticed.
Do I continue and add all  I find in next few days as single additional post?

**Comment by AnthorNet** [comment]
Yes please, might help to get some correct spawn to make the mod loads specific areas

**Comment by kajahama** [comment]
This is probably everything I'm going to find for now.
No hurry in using this data, I was just combing throught the map and used the playtime to compile this list at same time.

Includes the area from original message.
Also includes the later spammed ones, that I deleted from the thread.

Additions:
-280,222 / -29,897 / 36m: Gas pillars around Yellow Power Slug are missing.
-267,599 / -180,681 / 10m: Gas pillars NE from Mercer Sphere are missing.
-218,427 / 24,200 / 88m: Gas pillars around Purple Power Slug are missing.
-216,627 / 127,790 / -8m: Gas pillars around Yellow Power Slug are missing.
-198,374 / -10,592 / 38m: Gas pillars around Purple Power Slug are missing.
-176,864 / 88,805 / 115m: Gas pillars around Purple Power Slug are missing.
-176,529 / -69,673 / 11m: Gas pillars around Yellow Power Slug are missing.
-169,812 / 206 / 205m: Gas pillars around Yellow Power Slug are missing.
-136,296 / -113,794 / 31m: Gas pillars around Blue Power Slug are missing.
-133,099 / -93,390 / 5m: Gas pillars around Mercer Sphere are missing.
-132,430 / -4,225 / 229m: Gas pillars around Yellow Power Slug are missing.
-118,481 / 74,930 / 170m: Gas pillars around BP_DropPod1_9 are missing.
-116,298 / -160,392 / 10m: Gas pillars around Blue Power Slug are missing.
-94,709 / 40,338 / 198m: Gas pillars around BP_DropPod6 are missing.
-67,362/ 29,824 / 197m: Gas pillars around Mercer Sphere are missing.
-62,254 / 74,170 / 204m: Gas pillars around Yellow Power Slug are missing.
-44,534 / 41,317 / 215m: Gas pillars around Purple Power Slug are missing.
54,817 / 14,339 / 135m: Gas pillars around Yellow Power Slug are missing.
65,707 / 64,887 / 359m: Gas pillars around Purple Power Slug are missing.
68,007 / 6,851 / 134m: Gas pillars around Blue Power Slug are missing.
85,100 / 14,002 / 145m: Gas pillars around Blue Power Slug are missing.
120,698 / -126,196 / 194m: Gas pillars around Purple Power Slug are missing.
127,953 / -46,916 / 132m: Gas pillars around Somersloop are missing.
133,219 / -81,603 / 123m: Gas pillars around Blue Power Slug are missing.
150,971 / -88,202 / 130m: Gas pillars around Purple Power Slug are missing.
151,636 / -73,482 / 112m: Gas pillars around Somersloop are missing.
178,969 / -91,003 / 92m: Gas pillars around Yellow Power Slug are missing.

24,129 / 74,259 / 228m: Gas pillars around Somersloop are mostly missing.


Removals:
-89,783 / -146,644 / 46m: Gas pillars under BP_DropPod4_7 have been removed.
216,097 / -268 / -16m: Gas pillars N from BP_DropPod7 have been partly removed.

**Comment by kajahama** [comment]
Had to do one final outing and couple more.
Switching from exploration back to base building mode.

Additions:
-200,036 / -123,773 / 20m: Gas pillars around Yellow Power Slug are missing.
-154,156 / -62,050 / 48m: Gas pillars around Yellow Power Slug are missing.
104,883 / -32,946 / 141m: Gas pillars around Yellow Power Slug are missing.

-91,286 / 271,310 / -65m: Gas pillars around Yellow Power Slug are mostly missing.

**Comment by AnthorNet** [comment]
Added 232 new gas pillars
