### ISSUE TITLE
Deleting stock item stacks around drop pods causes edited save to crash game.

### ISSUE THREAD

**Issue by kajahama** [AnthorNet/SC-InteractiveMap#268]
# Issue
Trying to delete (some?) default item stacks that are on the map around drop pods now causes the game to crash while trying to load the edited save.
This might be just after 2022-10-21 update to SCIM.

There is currently ingame bug that causes some of these item stacks to respawn.
On 20th I successfully deleted stacks around BP_DropPod1_1 at 800, -440 and they stopped respawning.
On 22nd I tried to delete stacks around BP_DropPod34 at -1523, 2295, and this caused crash.
On 24th I tried to delete stacks around BP_DropPod10 at 2365, -3122, and this caused crash.

Deleting normal item stacks works.
Haven't tried to delete items around pods that don't respawn items.

Game crashing error on load:
`Assertion failed: mPerLevelDataMap.Contains( destroyedActorLevels.Key ) == false [File:D:/ws/SB-220602145101-842/UE4/Games/FactoryGame/Source/FactoryGame/Private/FGSaveSession.cpp]`

Possibly caused by commit?: Add new BP scripts exclusions
https://github.com/AnthorNet/SC-InteractiveMap/commit/d3632d4c4ac6b8c333839733309b79f18b5d4b24
If not, I would expect this to be game bug and not SCIM bug.

## Replication
Open save in SCIM with uncollected items around (bugged?) drop pod.
Delete the items with selection tool, delete. Doesn't matter if you move to loot crate or not.
Save in SCIM.
Load save in game.

### Actual Result
Game crashes while loading the edited save.

### Expected Result
Edited save loads succesfully.
Specific items don't respawn anymore.
This is what I was able to do on 20th with BP_DropPod1_1.

**Comment by AnthorNet** [comment]
Not related to that commit, but that bug is on my radar.
The new U6 save format only store objects after the player has visited the area, the same crash can be caused while clear slugs for examples and if they are not present in the save yet.
I'm looking into that, but that ca take some time to fix!

**Comment by kajahama** [comment]
Ok.

In this case there is a game side bug that causes the specific items pickup not to be saved properly, causing them to respawn when loading a save.
Also affects slugs, boulders etc. in some areas based on bugreport site.

And I was able to get rid of those items on that one pod with SCIM, then you updated and couldn't on two other pods.
So made a bug report, because I couldn't be sure if the crash was a change to SCIM or game bug.

Stock items stacks near pods I haven't been close enough to don't show up in SCIM (as they aren't included in the save yet), so cannot even try to delete them.

So in this case, a game side bug with saving, and then possible SCIM bug because of the new save format.

Not anything important or needing to fixed quickly, just something noticed when trying to "clear" map of extra items.

**Comment by AnthorNet** [comment]
I'm currently working on the collectables, turns out its old code so might need more time to get it cleaner. :D

**Comment by kajahama** [comment]
There currently seems to be ingame bug related to saving slugs, drop pod item stacks, boulders etc.
First time you go to a new chunk of map and collect slugs etc. the status change doesn't get saved properly, leading the changed stuff to respawn on next loading of a save.
Going to a chunk, saving and instantly loading the new save seems to make the changes stick most of the time from that point on in that chunk.

Trying to edit originally faulty save is what leads to those crashes when loading edited save.

So probably sit on this until the game bug is fixed or just straight close the bug.

**Comment by AnthorNet** [comment]
Most bugged in-game items were transmitted to CSS. But yes it's a game bug.
Collectables that could cause a crash from SCIM were fixed by not clearing non discovered areas.
