### ISSUE TITLE
Ingame blueprints removed with SCIM leave behind snapping boxes.

### ISSUE THREAD

**Issue by kajahama** [AnthorNet/SC-InteractiveMap#274]
# Issue
If a blueprint that hasn't had any of its items removed ingame, is removed as whole via SCIM, then when deploying more BP:s in Blueprint mode, the removed blueprints bounding boxes still show up ingame for snapping to.

This doesn't go away by building normally or new BP in same space and removing items.
Also doesn't go away by saving and reloading ingame.

## Replication
Place a blueprint ingame.
Save.
Remove the items of the blueprint in SCIM.
Load edited save in game.
Start deploying new blueprint at the same position.

### Actual Result
There is a empty blueprint snap box at the location of the SCIM deleted BP that can have new BP:s snapped to it.

### Expected Result
BP snap box is removed when the items are removed in SCIM.
Correction: Ingame the snap box is only removed when last original item of the BP is removed.
Original, Wrong: Preferrably the box is removed if even single item of the original BP deployed is removed like ingame behavior is.

**Comment by kajahama** [comment]
Addition: Removing most items via SCIM and then removing the last one(s) ingame removes the snapping box.

**Comment by kajahama** [comment]
Probably related to the "mBlueprintProxy" property and "PersistentLevel.FGBlueprintProxy_#" child objects for every buildable that has come from Blueprint deployment has.

So any "PersistentLevel.FGBlueprintProxy_#" that isn't referenced by any still in save buildables mBlueprintProxy property  should be deleted?

**Comment by kajahama** [comment]
Currently in quick testing removed the blueprint boxes, at least when I remove all the items for that deployed BP via SCIM.  

But didn't yet clear out old empty blueprint boxes with no contents.  
Loaded save with them in SCIM and just resaved back without any changes.  
Leftovers boxes from mass-delete via SCIM that contained deployed BP:s were still in the save after.  

But these were different saves.

So no new orphan BP boxes seem to happen, but old ones weren't cleared away yet.

**Comment by kajahama** [comment]
On the main save, after load and save without changes, the old leftover BP boxes / proxies were now gone after this last code commit.  
And other BP boxes were still there.


Also just did small scale tests on new save where:

Removed the whole BP in SCIM.  
First removed part of the BP in SCIM, and then rest ingame.  
First removed part of the BP ingame, then removed the rest in SCIM.  
First removed part of the BP ingame, then removed some more in SCIM and then removed rest ingame.  
Didn't remove anything in SCIM, just resaved and removed it ingame.

BP boxes disappeared in all cases when last item from the BP was removed.


So that part seems to work now right and the BP boxes/proxies don't disappear too early and disappear when they are meant to.  
And SCIM doesn't seem to cause issues for the ingame code related to the same.


So to me it would seem that this bug can be now closed as fixed.

**Comment by AnthorNet** [comment]
Nice, just testing if I can invalidate the bounding box, and will close after.
