### ISSUE TITLE
A Crude Oil Node Is Missing From The Interactive Map

### ISSUE THREAD

**Issue by saladm2** [AnthorNet/SC-InteractiveMap#276]
Hi, 

There is a normal crude oil node that is missing from the interactive map - it is located at coordinates -360, -2095

**Comment by kajahama** [comment]
You probably just have extractor on it already.  
Shows up fine on the map without save loaded and correct filters applied.  

The map doesn't show nodes with extractors already on them.  
That one was moved in U6, so the extractor you placed before that will be at different location.

**Comment by saladm2** [comment]
Thanks for the catch! I was looking at the map via my uploaded save and did already have an extractor on it =)
