### ISSUE TITLE
Road types - curved and double ramp

### ISSUE THREAD

**Issue by SMERKIN5000** [AnthorNet/SC-InteractiveMap#28]
These are three requests that kind of merge together but are also separate. 

1) Curved road. From the direction the foundation is pointing create a curve using the selected foundation. A choice in left or right curve required. Choices required could be how many foundations the curve should take in the left or right. Alternatively another option could be the degree increment each foundation pivots. I can currently do this with a hollow circle and using the Arc angle, however it requires me to locate a foundation which is the center to create the road, which adds an extra bunch of steps.

2) Double ramped roads. I would like to be able to create a ramped road which either goes on an incline or a decline. Because I would be starting from a 1m/2m/4m foundation I would like the choice of selecting which double ramp road to use (because the foundation I am starting from may not be the ramp size angle I want to use). 

3) The next extension of these suggestions would be a curved road using double ramp foundations. If this is not possible, someone also suggested suggested that we could do curved roads with 1m, 2m or 4m raise/drop per block. This would then make it easy in game to apply the double ramps.

**Comment by AnthorNet** [comment]
Angles needs to be fixed before we go further on that.
Ramps don't have an angle that goes into the direction they go up.

Need to test them one by one!

**Comment by SMERKIN5000** [comment]
Understand. The curved road would be worthwhile proceeding with and also the alternate suggestion in point 3 with the raise/drop of the foundation which would make it easy to adapt them ingame to ramps.

**Comment by AnthorNet** [comment]
Clearly having some good ideas on how to implement, dependencies are in the way to properly handle it :p

**Comment by AnthorNet** [comment]
To make curve I think we need to pivot from the external foundation, by dividing the length by the angle.

**Comment by AnthorNet** [comment]
And we still have to implement the curvy step now :p

**Comment by SMERKIN5000** [comment]
I tested the new additions, very nice.

**Comment by SMERKIN5000** [comment]
Freaking awesome work.
