### ISSUE TITLE
Slugs and collectibles not updating on my save file

### ISSUE THREAD

**Issue by Robhellspawn** [AnthorNet/SC-InteractiveMap#281]
# Issue
I collect the slugs in-game and subsequently save, load the save file in the map and the slugs are still being shown as not collected

### Expected Result
Slug icons to disappear after collecting just like the others have already.

**Comment by kajahama** [comment]
Are you sure this isn't just the current ingame saving bug?  
There has been a bug in the save code for some time that causes it to not always save collectibles, flora, enemies, boulders and deposits correctly after you first time interact with them.  
And couple of places will never save correctly and will always respawn on load.

Load the same save that didn't show the slugs as collected, and go see if the specific slugs have respawned.
