### ISSUE TITLE
Excessive VRAM memory usage

### ISSUE THREAD

**Issue by tigrouind** [AnthorNet/SC-InteractiveMap#283]
# Issue
I have notified Interactive Map becomes slow after a short period of time and use lot of VRAM.

## Replication
1. Open a save with a big factory (no need of a mega factory)
2. Zoom in and out on the map for one minute on crowded areas.

### Actual Result
VRAM usage goes really high (8-10 GB) quickly.
The map freeze from time to time, especially after tab switching.

![Task Manager](https://github.com/AnthorNet/SC-InteractiveMap/assets/2211721/2167a689-188e-4374-bc93-8257db18969c)
This is with very few tabs and programs running in the background.
I have 32 GB of RAM and a 1080 TI so available memory should not be issue.

### Expected Result
VRAM usage stay reasonable, no freezes (eg: Google Maps stays below 1 GB).

**Comment by AnthorNet** [comment]
Yeah but Google maps doesn't draw thousands of polygon, I'm doing a whole lot of optimisation every now and then, but not sure much can be done.

Have you tried lowering the polygon details under options?

**Comment by tigrouind** [comment]
I have tried low detail mode but it does not really help (I did a full refresh and make sure it's applied correctly (eg: buildings now looks like a dummy square). GPU usage still reach 10GB after several zoom in / out.
I understand it does lot of rendering calls but I don't think it should use that much memory.
Would there be a possibility there is some memory leak ? (eg: non disposed objects / buffers)

Can you reproduce it at your side ?

**Comment by AnthorNet** [comment]
Just tested some Zoom In and Out, and the memory was moving back and forth as expected, did not notice any excessive usage?
Can I get your save to run more specific tests?

**Comment by tigrouind** [comment]
@AnthorNet : I'm unsure why you closed the topic because issue is still there: 
![image](https://github.com/user-attachments/assets/be2dfe84-db28-4f19-bbef-b8de540646b2)
With just a small amount of zoom in / out.

**Comment by AnthorNet** [comment]
To ease 1.0 issues, and still cannot reproduce...

**Comment by Speedy37** [comment]
@tigrouind  this is most likely a bug in your GPU driver

**Comment by tigrouind** [comment]
> @tigrouind this is most likely a bug in your GPU driver

Thank you. I was using 537.34 (2023.9.12) and upgraded to 561.09 (2024.9.11). It fixed the issue.

Please note that I was already using latest driver when this ticket was created and even updated afterwards. It took NVidia a while to fix this.
