### ISSUE TITLE
Hog and spitter research appears as not available yet while they have been already researched

### ISSUE THREAD

**Issue by tigrouind** [AnthorNet/SC-InteractiveMap#284]
# Issue
Hog and spitter research appears as not available yet while they have been already researched

![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/2211721/3a00670d-352d-429b-abc3-02b8b2d7467a)

![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/2211721/79f50582-5401-4f78-b2db-3d8748529398)

Here is the items SCIM is looking for : 
```
Research_ACarapace_2_C
Research_ACarapace_3_C
Research_AO_DNACapsule_C
Research_AO_Hatcher_C
Research_AO_Hog_C (missing)
Research_AO_Pre_Rebar_C
Research_AO_Spitter_C (missing)
Research_AO_Stinger_C
Research_AOrganisms_2_C
Research_AOrgans_2_C
Research_AOrgans_3_C
```

I have those in my save (excluding the ones above) : 

```
Research_ACarapace_0.Research_ACarapace_0_C
Research_ACarapace_1.Research_ACarapace_1_C
Research_ACarapace_2_1.Research_ACarapace_2_1_C
Research_AOrganisms_1.Research_AOrganisms_1_C
Research_AOrgans_0.Research_AOrgans_0_C
Research_AOrgans_1.Research_AOrgans_1_C
```

**Comment by AnthorNet** [comment]
They were modified sometime around U6/7 if I remember so we only keep the new one.
