### ISSUE TITLE
UPDATE 8 - KNOWN ISSUES

### ISSUE THREAD

**Issue by AnthorNet** [AnthorNet/SC-InteractiveMap#288]
- [x] Host player pathName not found (gameState mmissing extra bytes)
- [x] SubSytem have changed names (Eg: UnlockSubSytem vs unlockSubSytem)
- [x] Old megaprints don't paste (Writing error)
- [x] SubLevel saving takes longer than expected due to small size worker transfer
- [X] Vehicles have unknown missing bytes (Was UE physics)
- [ ] Gas Pillar are not handled (Yet!)
- [x] Foliage sub system seems to have changed format
- [x] Blueprint new format?
- [x] New Advanced Game Mode missing (#289)
- [ ] Priority fuse not handled (Mainly UI)
- [ ] Hypertube teleporter not working anymore

**Comment by AnthorNet** [comment]
Added: Old megaprints don't paste (Writing error)

**Comment by AnthorNet** [comment]
Added: Hypertube teleporter not working anymore

**Comment by Sadumon** [comment]
On the experimental version of the map, all of the hard drives show no material requirements (the power is still there).

The Power Towers are showing as "unknown building".

**Comment by AnthorNet** [comment]
> On the experimental version of the map, all of the hard drives show no material requirements (the power is still there).
> 
> The Power Towers are showing as "unknown building".

Fixed now

**Comment by AnthorNet** [comment]
Fixed:  SubSytem have changed names (Eg: UnlockSubSytem vs unlockSubSytem)

**Comment by AnthorNet** [comment]
Fixed: SubLevel saving takes longer than expected due to small size worker transfer

**Comment by ghost** [comment]
Hi! In the experimental version of the map flora regenerates in the saved game. Is this related to "Foliage sub system seems to have changed format"? Thanks!

**Comment by ShamusTheTinker** [comment]
In experimental the loaded map does not recognize which hard drives have been collected.

**Comment by wiggles5289** [comment]
> In experimental the loaded map does not recognize which hard drives have been collected.

Same here but when right clicking the icon to open or close the icon, it states its been opened(icon shows closed) but gives the option to "close" it. The bool operator shows it as opened on the advanced debug page. Closing then Opening command makes the icon the correct state.

**Comment by AnthorNet** [comment]
> Hi! In the experimental version of the map flora regenerates in the saved game. Is this related to "Foliage sub system seems to have changed format"? Thanks!

Related, yes but if you don't touch the flora it should not affect the save.



> In experimental the loaded map does not recognize which hard drives have been collected.

Testing :)

**Comment by AnthorNet** [comment]
> In experimental the loaded map does not recognize which hard drives have been collected.

I've not been able to reproduce any bugs on Hard Drive?

**Comment by ghost** [comment]
Unfortunately, I cleared out the areas around my factories and along some roads so now if I use the Interactive Map and save my game, it all regenerates each time. No worries, I realize this experimental release. I was just curious. Hopefully it'll get fixed some time. I don't do this often, once a day maybe,  and I just have to spend few minutes each time with nukes, to clear it out again:) Thanks!

**Comment by AnthorNet** [comment]
Can I get your save? And if you have a backup from before you touch the flora.
Flora are not easy to test but I'll get on it :)

**Comment by ShamusTheTinker** [comment]
> > In experimental the loaded map does not recognize which hard drives have been collected.
> 
> I've not been able to reproduce any bugs on Hard Drive?

Same problem is happening when I click on dropped items.  Nothing I've picked up shows removed on the map.  I've cleared all of the hard drives and dropped items around them around the easy area where I started and even the latest drives I've picked up don't disappear on the map.

**Comment by ghost** [comment]
> 

I don't have a save from before I started removing the flora, it's been months. Here are two current saves, before and after:
https://drive.google.com/file/d/1cWneupMOoTfyWqsqADu5_A1uN5bX-13y/view
It's enough to just save the file for the plants to reappear, even without making any changes to the world. Please let me know if you need anything else or if the Google link doesn't work for you, I'm not sure if I can upload directly to Github, I don't have any projects here. Cheers!

**Comment by AnthorNet** [comment]
Ugly fixed: Host player pathName not found (gameState mmissing extra bytes) :D

**Comment by Nodagoscha** [comment]
> > In experimental the loaded map does not recognize which hard drives have been collected.
> 
> I've not been able to reproduce any bugs on Hard Drive?

I have the same issue.
Save: https://drive.google.com/file/d/1Gx11EDY23xAWTVuzWI5ZnM5Rr65KnXpM/view?usp=sharing
HDD ar player possition is collected

SOLVED: My fault. Didn't switch to experimental!

**Comment by Worminator71** [comment]
> Can I get your save? And if you have a backup from before you touch the flora. Flora are not easy to test but I'll get on it :)

I've had this same issue and I have two files available - one with the foliage deleted and then with the foliage regrown after saving in SC

**Comment by Worminator71** [comment]
> > Can I get your save? And if you have a backup from before you touch the flora. Flora are not easy to test but I'll get on it :)
> 
> I've had this same issue and I have two files available - one with the foliage deleted and then with the foliage regrown after saving in SC

[U8 Full Vanilla - Foliage Regrown_CALCULATOR.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11931302/U8.Full.Vanilla.-.Foliage.Regrown_CALCULATOR.zip)

**Comment by ghost** [comment]
Here is another from me. The other one was incomplete or something?
https://drive.google.com/file/d/1xqVr6TR8GwxtLdBFHDEYDCF7ZKjTAhMX/view?usp=sharing

**Comment by AnthorNet** [comment]
All good, I(ll try to fix it soon, but got sidetracked by priority parsing bugs :)

**Comment by ghost** [comment]
Thank you :)

**Comment by AnthorNet** [comment]
Good news ! The Foliage should not respawn each time :)
Yet the restore function still needs to be fixed to work properly under U8

**Comment by ghost** [comment]
Confirming that the foliage no longer respawns!!! Thank you :)

**Comment by AnthorNet** [comment]
Fixed: Foliage sub system seems to have changed format (Most likely)

**Comment by ShamusTheTinker** [comment]
> > In experimental the loaded map does not recognize which hard drives have been collected.
> 
> I've not been able to reproduce any bugs on Hard Drive?

I can upload my save file this evening if it would help.  My save was converted to experimental and was not started on experimental.

**Comment by ShamusTheTinker** [comment]
> > > In experimental the loaded map does not recognize which hard drives have been collected.
> > 
> > 
> > I've not been able to reproduce any bugs on Hard Drive?
> 
> I can upload my save file this evening if it would help. My save was converted to experimental and was not started on experimental.
[Fourth.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11941739/Fourth.zip)

Ok, here is my save file.

**Comment by Hemito** [comment]
Not sure how to properly describe the procedure.
I created a new game, deleted resources near the fallen load with spawning them next to me.
Loaded this save, everything is fine.
Game crashes without error when trying to save

**Comment by AnthorNet** [comment]
> Not sure how to properly describe the procedure. I created a new game, deleted resources near the fallen load with spawning them next to me. Loaded this save, everything is fine. Game crashes without error when trying to save

Can I get your save?

**Comment by Hemito** [comment]
[Update 8_autosave_2_CALCULATOR.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11980987/Update.8_autosave_2_CALCULATOR.zip)

**Comment by AnthorNet** [comment]
Hey, did not crash for me, but seems that you encountered an early parsing bug. Could you send me the original save, and also try to clear your cache see if it still does the same error if you try again?

**Comment by Hemito** [comment]
> Hey, did not crash for me, but seems that you encountered an early parsing bug. Could you send me the original save, and also try to clear your cache see if it still does the same error if you try again?

I'd love to, but you'll have to tell me how to do it...

**Comment by AnthorNet** [comment]
You can reload the map with CTRL+SHIFT+R to reload and flush the cache to get the last version.

**Comment by Hemito** [comment]
Now try again?
Edit; Wow, is Work! Thank you, I'm sorry, it seems my appeal was redundant, but I'm glad that you helped me

**Comment by AnthorNet** [comment]
Cool!
Did you remove the same items as before? Just to confirm nothing is wrong on my side to check further?

**Comment by Hemito** [comment]
> Cool! Did you remove the same items as before? Just to confirm nothing is wrong on my side to check further?

Yes, I deleted a group of items and saved after that. If it comes back I will write.

**Comment by Hemito** [comment]
> Cool! Did you remove the same items as before? Just to confirm nothing is wrong on my side to check further?

Strange, the problem has returned, I can’t say exactly under what circumstances it happens, but it happens when I move lying objects, here is my save, which is intact. Try to remove all lying objects on the map, teleporting them to yourself, and then save
[UpD8.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11988306/UpD8.zip)

**Comment by except134** [comment]
Hello, calculator stucks on loading my save file

[https://drive.google.com/file/d/1GVRg7yReOLbYCsFkDi-4ILX62JWQG_2P/view?usp=drive_link](url) Screenshot
[https://drive.google.com/file/d/1GX5keh31WMcsy77-HS9EAVjic9VcLfde/view?usp=drive_link](url) My save file

**Comment by except134** [comment]
Hello, calculator stucks on loading my save file

[https://drive.google.com/file/d/1GVRg7yReOLbYCsFkDi-4ILX62JWQG_2P/view?usp=drive_link](https://drive.google.com/file/d/1GVRg7yReOLbYCsFkDi-4ILX62JWQG_2P/view?usp=drive_link) Screenshot
[https://drive.google.com/file/d/1GZB5D68wa71A_Uhn9HfvsQhF8H2oSfYG/view?usp=sharing](https://drive.google.com/file/d/1GZB5D68wa71A_Uhn9HfvsQhF8H2oSfYG/view?usp=sharing) My save file

**Comment by AnthorNet** [comment]
> Hello, calculator stucks on loading my save file
> 
> https://drive.google.com/file/d/1GVRg7yReOLbYCsFkDi-4ILX62JWQG_2P/view?usp=drive_link Screenshot https://drive.google.com/file/d/1GZB5D68wa71A_Uhn9HfvsQhF8H2oSfYG/view?usp=sharing My save file

Should be fixed :)

**Comment by except134** [comment]
> > Hello, calculator stucks on loading my save file
> > https://drive.google.com/file/d/1GVRg7yReOLbYCsFkDi-4ILX62JWQG_2P/view?usp=drive_link Screenshot https://drive.google.com/file/d/1GZB5D68wa71A_Uhn9HfvsQhF8H2oSfYG/view?usp=sharing My save file
> 
> Should be fixed :)

Thank you!! Fixed!

**Comment by nilshomeier** [comment]
Hi, I've just found, that if you copy and paste a blueprint and later use the blueprint delete mode, it will delete ALL of the instances, the original one and all those, that have been copy and pasted.

**Comment by iliasaw** [comment]
My save does not want to load on the map and just hangs. At first it's very slow and then it hangs on the 
MERGING INFLATED CHUNKS
https://i.imgur.com/Z7sdx8K.png

Save:
https://mega.nz/file/aBhkCZSa#E_ksss4DMVcAPtEa1w2M66kOGape6o67GppmOLC1xEw

**Comment by AnthorNet** [comment]
> My save does not want to load on the map and just hangs. At first it's very slow and then it hangs on the MERGING INFLATED CHUNKS https://i.imgur.com/Z7sdx8K.png
> 
> Save: https://mega.nz/file/aBhkCZSa#E_ksss4DMVcAPtEa1w2M66kOGape6o67GppmOLC1xEw

Checked and I believe it seems to be a browser limitation, I'll check sooner than later if I can split the ArrayBuffer easily without breaking everything.

**Comment by galih9** [comment]
hello, i tried to clear all summerslop and mercer sphere, but only 65 of them are cleared, not the entire 150, is it impossible to clear all the wip item? the voice kinda annoying and freak me out

**Comment by AnthorNet** [comment]
> hello, i tried to clear all summerslop and mercer sphere, but only 65 of them are cleared, not the entire 150, is it impossible to clear all the wip item? the voice kinda annoying and freak me out

Hey, due to how the world streaming works now only visited area can be wiped. Once you visit more, you'll be able to delete more. Generating non visited area, is a more complex work that can hardly be done.

**Comment by zxcx225** [comment]
> > My save does not want to load on the map and just hangs. At first it's very slow and then it hangs on the MERGING INFLATED CHUNKS https://i.imgur.com/Z7sdx8K.png
> > Save: https://mega.nz/file/aBhkCZSa#E_ksss4DMVcAPtEa1w2M66kOGape6o67GppmOLC1xEw
> 
> Checked and I believe it seems to be a browser limitation, I'll check sooner than later if I can split the ArrayBuffer easily without breaking everything.

Any update on this?

**Comment by AnthorNet** [comment]
Not really, after testing it seems to be related to our inflating library which doesn't seems to output the correct chunk length. Still need more testing.

**Comment by Ryder17z** [comment]
is the missing bytes for vehicles the reason why they do not display on the map but only as stats?

**Comment by AnthorNet** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/30e8dff7-e928-43f7-a1b1-cd004bf97a64)
Works on my test.

If you still have the issue, please open an issue with your save?
