### ISSUE TITLE
Hard drive requirements wrong on Experimental Branch

### ISSUE THREAD

**Issue by b-steiner** [AnthorNet/SC-InteractiveMap#291]
# Issue
 * Requirements for Crash Sites/Harddrives are not correct in Update8 Experimental. Example: Crash Site "BP_DropPod12" (-4.707/-76.302) lists "No requirement" but requires 10 blackpowder.

**Comment by AnthorNet** [comment]
This particular one should be fixed, a lot of internal renaming has happened and some are still bugged on my back office. I'll try to rewrite all that tomorrow

**Comment by Xebtria** [comment]
This still seems to be bugged, no hard drive on experimental seems to have any requirements, except for power. on early access it shows up correctly.

**Comment by AnthorNet** [comment]
Really fixed this time :D
