### ISSUE TITLE
Overclocking fuel generator doesn't affect the grid

### ISSUE THREAD

**Issue by fsimancik** [AnthorNet/SC-InteractiveMap#292]
![generator](https://github.com/AnthorNet/SC-InteractiveMap/assets/2399129/524da794-e9f7-44ff-954e-6d77944afc6d)

# Issue

When you overclock a fuel generator using the SCIM's "Update clock speed" functionality, the grid doesn't get updated to the new value. This is in experimental Update 8.

See the attached screenshot for example.

## Replication

1. Overclock a running fuel generator from 100% to 150% using the SCIM's "Update clock speed" functionality.
2. Download the save and open it in Satisfactory.
3. Inspect the grid to which the generator is connected (e.g. by clicking on the generator itself).

### Actual Result
The grid will show the old power value even though the generator shows it is now providing 225 MW.

### Expected Result
The grid should have been updated to include the new power value provided by the generator.

**Comment by AnthorNet** [comment]
Did you wait for the next fuel item to be used?

**Comment by fsimancik** [comment]
Yes. The reason I got interested in this was that I have a power plant that got eaten by landscape in an earlier update, and I now wanted to overclock the generators but I am not able to physically reach them.

I played for a while and was trying multiple things to get the power value fixed. Like deleting a wire that goes to the power plant and rebuilding it. Or causing a power trip and restarting the grid. None of this helped.

I then started experimenting with a test generator in the picture above. The only thing that actually worked was to delete and rebuild the wire that goes directly to the generator.

**Comment by AnthorNet** [comment]
Can I get you test save?
I don't see anything in the circuits that could potentially cache the generated power data

**Comment by fsimancik** [comment]
Sure, I have attached the save from which I made that screenshot. I am standing there right next to the test generator.
[overclocking_test.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11916714/overclocking_test.zip)

I noticed there is a property called mDynamicProductionCapacity in Advanced Debug.powerInfo that remains at 150 for the generator. Is this perhaps related?

**Comment by AnthorNet** [comment]
I've seen that one and was wondering, but in my test it wasn't filled. I'll deploy a temporary fix deleting it see if it fixes it.

**Comment by AnthorNet** [comment]
Deployed, if you can test if it works better?

**Comment by fsimancik** [comment]
I just tried it, but I don't see any difference. The mDynamicProductionCapacity property is still set to 150 in the edited save.

**Comment by AnthorNet** [comment]
Totally my fault, I was in a rush before going to pickup the kids and did a bad copy/paste :D
I believe it should be removed now, and hopefully it will force the game to recalculate the values.

**Comment by fsimancik** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/2399129/effa6fb6-af9b-4384-9781-2b4e1e582b6d)

Well, now it generates 0 MW and doesn't burn fuel at all (the progress bar is just stuck).

**Comment by AnthorNet** [comment]
Right! Got a new one for you :)

Now I'm wondering if I should also apply this to producer with the mTargetConsumption property...

**Comment by fsimancik** [comment]
That worked. Thanks for fixing!
