### ISSUE TITLE
Delete option for WIP items (Somersloop, Mercer Sphere)

### ISSUE THREAD

**Issue by tranermr** [AnthorNet/SC-InteractiveMap#293]
Would it be possible to add a delete option to the Somersloop and Mercer Sphere items? Right clicking on items or animals a "delete" option appears in the context menu, but I cannot find a similar option for the WIP items.

This would be of benefit because it would allow players to avoid the voice prompts until 1.0 without entirely muting the AI voice.

Thanks for your great work!

**Comment by AnthorNet** [comment]
Under Options > Collectables, use the clear option.
Since a couple of Updates, you can only clear in the areas you already have visited.
