### ISSUE TITLE
> > > In experimental the loaded map does not recognize which hard drives have been collected.

### ISSUE THREAD

**Issue by AnthorNet** [AnthorNet/SC-InteractiveMap#294]
> > > In experimental the loaded map does not recognize which hard drives have been collected.
> > 
> > 
> > I've not been able to reproduce any bugs on Hard Drive?
> 
> I can upload my save file this evening if it would help. My save was converted to experimental and was not started on experimental.
[Fourth.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11941739/Fourth.zip)

Ok, here is my save file.

_Originally posted by @ShamusTheTinker in https://github.com/AnthorNet/SC-InteractiveMap/issues/288#issuecomment-1619231999_

**Comment by AnthorNet** [comment]
Opening a new one so we can get proper reproduction :)

**Comment by AnthorNet** [comment]
Could be a game bug: https://questions.satisfactorygame.com/post/648b6ae587a1e63b6cee42e1

**Comment by imakin** [comment]
i dont think it's a game bug because it also occur if you start a new one, to test:
- start a new save in update8
- collect harddrive on nearest location then confirm if its collected in game
- save game and open save in the webapp (hard drive looks uncollected)
- back to the game, reload save and revisit the harddrive and in game it is already collected

**Comment by ShamusTheTinker** [comment]
> i dont think it's a game bug because it also occur if you start a new one, to test:
> 
> * start a new save in update8
> * collect harddrive on nearest location then confirm if its collected in game
> * save game and open save in the webapp (hard drive looks uncollected)
> * back to the game, reload save and revisit the harddrive and in game it is already collected

That has been my experience.  I've taken to turning off the hard drives on the map while I play.

**Comment by ShamusTheTinker** [comment]
> > i dont think it's a game bug because it also occur if you start a new one, to test:
> > 
> > * start a new save in update8
> > * collect harddrive on nearest location then confirm if its collected in game
> > * save game and open save in the webapp (hard drive looks uncollected)
> > * back to the game, reload save and revisit the harddrive and in game it is already collected
> 
> That has been my experience. I've taken to turning off the hard drives on the map while I play.

I am an idiot.  I just hit the Game Branch button to change to experimental and now it shows properly which hard drives are still there.

**Comment by imakin** [comment]
> > > i dont think it's a game bug because it also occur if you start a new one, to test:
> > > 
> > > * start a new save in update8
> > > * collect harddrive on nearest location then confirm if its collected in game
> > > * save game and open save in the webapp (hard drive looks uncollected)
> > > * back to the game, reload save and revisit the harddrive and in game it is already collected
> > 
> > 
> > That has been my experience. I've taken to turning off the hard drives on the map while I play.
> 
> I am an idiot. I just hit the Game Branch button to change to experimental and now it shows properly which hard drives are still there.

i probably made the same mistake. I'll test again when i reach my gaming machine
