### ISSUE TITLE
Add fauna spawn locations to map

### ISSUE THREAD

**Issue by yeSpud** [AnthorNet/SC-InteractiveMap#295]
Can the spawn locations of various types of fauna be added to the map (including altitude to differentiate what spawns in caves)?

This is mainly so I can be prepared for the cats...

**Comment by AnthorNet** [comment]
You can find them here:
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/31ced2cc-d515-48b0-94ab-f86c902b141a)

That said, the game don't tell which one is which one :)

**Comment by yeSpud** [comment]
Do you need to import a save to view that menu?

**Comment by AnthorNet** [comment]
Yes you need. I'm currently not keeping them in the back-office.
