### ISSUE TITLE
Deleting some dropped items break the save parsing

### ISSUE THREAD

**Issue by AnthorNet** [AnthorNet/SC-InteractiveMap#296]
> Cool! Did you remove the same items as before? Just to confirm nothing is wrong on my side to check further?

Strange, the problem has returned, I can’t say exactly under what circumstances it happens, but it happens when I move lying objects, here is my save, which is intact. Try to remove all lying objects on the map, teleporting them to yourself, and then save
[UpD8.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/11988306/UpD8.zip)

_Originally posted by @Hemito in https://github.com/AnthorNet/SC-InteractiveMap/issues/288#issuecomment-1626774180_

**Comment by AnthorNet** [comment]
From early testing and to not forget it happens when the map saves collectables that are not found in game.

**Comment by PuckyBoy** [comment]
Not sure if related but when I removed all lying objects with the save editor (Update 8) the game begin to take really long time to make a save. I can confirm that deleted object contain objects not in game (at least not accessible).

(EDIT: To compare, manually retrieving accessible in game object didnt slow the saving process)

**Comment by AnthorNet** [comment]
Yeah it should be related, test needs to be made to be able to find a specific object triggering the bug. 
It could be an in-game bug too.

Once we found a very specific one to replicate, we can start figuring what it the best way to fix it.

**Comment by AnthorNet** [comment]
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable_36
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable425_1
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable429_5
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable428_4
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable424_0
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable427_3
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable426_2
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable437
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable438
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable436
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable435
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable_27
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable_26
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable431_7
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable430_6
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable433_9
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable432_8
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable434
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable440
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable441
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable442
- [ ] Persistent_Level:PersistentLevel.FGItemPickup_Spawnable439

Added potential list of bugged items to be tested.

**Comment by AnthorNet** [comment]
After more testing it turns out it's 50/50 a game bug. Some items aren't saving in-game and are respawning after reload.
Those one makes the deleting with calculator buggy...

**Comment by AnthorNet** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/3903df2c-63a3-426c-bf2b-9f332e1bc071)
Old map of a previous test for in-game bugged items... I'll try to find them all and make a proper list to prevent SCIM deletion...

**Comment by AnthorNet** [comment]
Should be fixed, bugged items are prevented from being deleted on SCIM.
