### ISSUE TITLE
Hard Drives

### ISSUE THREAD

**Issue by GordoTheGreat** [AnthorNet/SC-InteractiveMap#297]
# Issue
Not recognizing the collected hard drives. I updated to Update 8 about 2 weeks after Update 8 came out. I have not updated within update 8 after the first update. After the update, I have loaded saves and it noted which hard drives were collected. About 2 days ago, when I tried uploading a save, the hard drives started saying I have not collected any drives. I tried old saves that I have previously used to see if they still work, but even those saves no longer show which drives are collected, both from a game converted from Update 7 (and 6), and one created in Update 8.

## Replication
1. Import a game save to the web page.
2. Select "collectables" on the right hand side.
3. look at how many hard drives there are.

### Actual Result
97

### Expected Result
55/97 or 2/97 depending on whither I am using the game converted from Update 7 or the game created in update 8.

**Comment by AnthorNet** [comment]
Are you sure you are still on the experimental branch of the map?

EDIT: Also needs a save for checking!
