### ISSUE TITLE
Clicking a Radar Tower irreversibly makes the view orange

### ISSUE THREAD

**Issue by Ondrejtra** [AnthorNet/SC-InteractiveMap#300]
# Issue
Clicking a Radar Tower (not its UI, but the building visual) causes a transparent orange overlay over the entire map view.

Deleting the Radar Tower doesn't remove the overlay. Only loading a save or refreshing the site clears the overlay.

## Replication
1. Load a save file with a Radar Tower
2. Left-click on it (repeatedly)

### Actual Result
The view turns orange, even more orange with every subsequent click

### Expected Result
The view does not turn orange

**Comment by AnthorNet** [comment]
Ooops it was only supposed to show the radar overlay on mouse over!

**Comment by AnthorNet** [comment]
Fixed for Experimental
