### ISSUE TITLE
M.A.M. Alien Organism research: hog and splitter research not parsed 

### ISSUE THREAD

**Issue by ValnyrTopwich** [AnthorNet/SC-InteractiveMap#301]
# Issue
When I load my save game into the SCIM, the hog and splitter research are shown as locked although I have unlocked them already in the game.

## Replication
1. I load the save game in the interactive map editor

### Actual Result
I see the hog and splitter research as locked

### Expected Result
I expect the hog and splitter research unlocked. Attached is the save game. 
[First.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/12285729/First.zip)

**Comment by AnthorNet** [comment]
Yep, they were renamed at some point, I wonder if we should just alias them?

**Comment by ValnyrTopwich** [comment]
Yeah I suppose that would be the easiest.
