### ISSUE TITLE
Show Ground Items Around Crash Sites

### ISSUE THREAD

**Issue by StyxnStones** [AnthorNet/SC-InteractiveMap#302]
It would be nice to be able to see the items on the ground around the world and around crash sites when you hover over the hard drive icons.

**Comment by dtminnaar** [comment]
I realise this does not match your request, but you can currently see the dropped items.

You need to load your save game, then there is a new button under "Collectables" that you can toggle:
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3232307/c2ca61e0-5d09-4e99-a6ac-6010c7803e05)

That will show you dropped items around the harddrives:
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/3232307/09828add-b5a7-4c09-ae25-91765744a6e8)
