### ISSUE TITLE
Moving and offsetting does not work.

### ISSUE THREAD

**Issue by XanderKehoe** [AnthorNet/SC-InteractiveMap#304]
# Issue
Moving or offsetting position of building/factory does not work.

## Replication
1. Select a large building/factory (not sure if size has anything to do with it, I noticed it with a large building).
2. Move or offset the position

### Actual Result
Nothing happens, the selected area does not move.

### Expected Result
The selected factory/building to move respective to the input I provided.

**Comment by AnthorNet** [comment]
I cannot reproduce on my test save, could you please share your save?

**Comment by XanderKehoe** [comment]
[World 3_280823-172841_SUPPOSED_ADJUSTED.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/12467953/World.3_280823-172841_SUPPOSED_ADJUSTED.zip)

I was trying it on the large building on the east side of the desert. I originally build it raised up because I thought I'd need to not run into the big rocks, but turns out I wasn't going to hit them so I tried lowering it using the map editor.

**Comment by AnthorNet** [comment]
Still cannot reproduce with your save :( Anything popping into your browser console?

**Comment by XanderKehoe** [comment]
Just tried this again and didn't have an issue. Not sure why it didn't work before, I closed the whole website and re-opened it with the save again and still had issues, so I made this ticket. But as of now its working so I wouldn't worry about it for now.
