### ISSUE TITLE
[Feature Request] Remove Mod Warning from "safe" saves

### ISSUE THREAD

**Issue by HgAlexx** [AnthorNet/SC-InteractiveMap#305]
Hello,

A while back I only used PermaDay, but I had to disable mods to play with a friend. Now Satisfactory warns me every times I load the save.

Since I know for certain that the save is "safe", it would be nice to have a option to remove the warning, if possible of course.

Thank you !

**Comment by AnthorNet** [comment]
Done internally, will be under Options > Game rules

**Comment by HgAlexx** [comment]
Working perfectly ! thx !
