### ISSUE TITLE
Outdated mods, partially handled buildings

### ISSUE THREAD

**Issue by nbali** [AnthorNet/SC-InteractiveMap#306]
# Issue
There are some mods that contain unrecognized buildings, and has got only partial support

## Replication
For example build "Build_Constructor_Mk3.Build_Constructor_Mk3_C" from "Industrial Evolution"

### Actual Result
It's shown as an unindetified building.

### Expected Result
Shown as a building from the mod as it happens for other building from the same mod.

---

So should I report such issues here because every building should be already handled or to the author of the mod?

**Comment by AnthorNet** [comment]
Hey
Sadly you need to check with mod author's as they get back office access.

If I were to do them for all mods, it would take me too much time :D

**Comment by nbali** [comment]
So is it limited to mod authors' only? I mean in some cases should be easier to just do it than to track someone down.

**Comment by AnthorNet** [comment]
I'll do it for this one, but won't be at the office until next week.

Was just saying it would be a good idea to ping the mod author too ;)
