### ISSUE TITLE
Schematics Not Saving

### ISSUE THREAD

**Issue by omayhemo** [AnthorNet/SC-InteractiveMap#307]
# Issue
Research, Schematics Tiers not unlocked when save is loaded.

## Replication
Using Update 7 save, I choose Research -> Schematics and unlock various Tiers.  
When loading the save in Update 7, the tiers are still locked.

### Actual Result
Schematic Tiers still require unlocking in the loaded saved game.

### Expected Result
I hoped to have all the Tiers I chose to unlock on the InteractiveMap unlocked in game when the exported saved game was loaded.

**Comment by AnthorNet** [comment]
Hey,
I'm currently out of the office but could you send both the original save and the saved one.

I'll make a check as soon as I get back next week.
