### ISSUE TITLE
Options:Hotbar does not display customizer skins, materials and patterns.

### ISSUE THREAD

**Issue by ehoffman2** [AnthorNet/SC-InteractiveMap#308]
# Issue
Options:Hotbar does not display slots that are set to customizer skins, materials or patterns.  You only see blank slots.

## Replication
- Load save game with some hotbar slots set to specific customizer meterials, pattern, or skins (FICSMAS)
- Click "Options", "Hotbar" tab.

### Actual Result
All the slots that are assigned a customizer skin, material or pattern display as empty.

### Expected Result
Should display the proper customizer selections.

**Comment by HgAlexx** [comment]
Since last patch (8.2) the options panel no longer show any hotbars, which is really unfortunate since most players got respawned and we could really the hotbars copy/paste feature :)

**Comment by AnthorNet** [comment]
> Since last patch (8.2) the options panel no longer show any hotbars, which is really unfortunate since most players got respawned and we could really the hotbars copy/paste feature :)

That part should be fixed internally and cope up within one hour.

**Comment by AnthorNet** [comment]
Actually it will take more time as all the format has changed :D

**Comment by AnthorNet** [comment]
Patch incoming, it still does not show the materials ans patterns but should copy them anyway ;)

**Comment by HgAlexx** [comment]
Thank you!

**Comment by HgAlexx** [comment]
Unfortunately, pasting seams to only override existing (filled) slots on the destination character hotbars :(

**Comment by AnthorNet** [comment]
Not sure what you mean?

**Comment by HgAlexx** [comment]
I'm trying to copy/paste all hotbars from "host" to my new guest player, which only has 4 hotbars slot filled (from 1 to 4 on the first hotbar).
I click copy on the host, and them paste on the new guest, only the 4 first slots are overridden with values from the host.

**Comment by AnthorNet** [comment]
Can I get your save?

**Comment by HgAlexx** [comment]
Sure!

I've just made a test.
I've loaded the save in-game and set items in all slots for hotbars 1 to 6, then tried again and it worked, all filled slots were properly overridden with values from host.

Here's the save with mostly empty hotbars on Guest:
https://www.dropbox.com/scl/fi/n6cylu5sssrt38c4lp39h/Open-World-2_171023-124533.zip?rlkey=9o1l6g38xvsq21bltyx02njou&dl=0

**Comment by AnthorNet** [comment]
Thanks, helped a lot, shortcuts weren't empty on my test save, no idea why!
I've deployed a fix, but cannot test in-game right; so if you could state if it doesn't break anything it would be good :)

**Comment by HgAlexx** [comment]
I used the save I shared with you, successfully copy/paste the hotbar, downloaded the save and launch the game... which decided to load me inside my old (host) player ... No idea why !
Anyway, everything seams to be working, except that I can't tell if the guest player is working properly atm :(

**Comment by HgAlexx** [comment]
Ok I know why:

https://www.reddit.com/r/SatisfactoryGame/comments/17a4zby/patch_notes_early_access_experimental_v0821_build/

:D

**Comment by AnthorNet** [comment]
Fixed internally
