### ISSUE TITLE
Show elevation/altitude on map

### ISSUE THREAD

**Issue by Nugman** [AnthorNet/SC-InteractiveMap#309]
Although the elevation/altitude is shown for resource nodes, it would be very handy to show the altitude along with the coordinates when hovering the mouse over any location on the map. 
This would help planning the minimum height of buildings in the sky like long-distance conveyors or train tracks.

**Comment by AnthorNet** [comment]
Would love too, but might prove to be harder than you think as I don't have direct access to the map height map. Fog uses one but I think it wasn't updated for a long time and is not accurate at all.
