### ISSUE TITLE
upgrading Mk1 pipes to Mk2 causes crashing

### ISSUE THREAD

**Issue by Hazrshield** [AnthorNet/SC-InteractiveMap#31]
im having problems opening a save file after using the pipe upgrade feature,
the world save is in the discord link since i cant attach a save file to Github (either im stupid or github is dunno) 
https://discord.com/channels/586017755338375178/674340269352681522/802604541152985088 
[FactoryGame.log](https://github.com/AnthorNet/SC-InteractiveMap/files/5860871/FactoryGame.log)

**Comment by AnthorNet** [comment]
Could you screen the crash log report window please?

**Comment by Hazrshield** [comment]
![image](https://user-images.githubusercontent.com/61326989/105616465-5af09480-5dd7-11eb-8b9e-e4a6f3d96b4d.png)
sorry its a little late hope this what you where asking for.

**Comment by AnthorNet** [comment]
Perfect 😍
It looks like a pipe has more spline data that it should have.
Right now my best guess is that something was caught in the conversion but shouldn't.

Investigation is eeded next week :)
