### ISSUE TITLE
COMPILING 5,051 SUB-LEVELS (99%)... stuck when trying to export a map

### ISSUE THREAD

**Issue by brokendruid** [AnthorNet/SC-InteractiveMap#310]
# Issue
The export feature of the interactive map has a bug when you try to export/save/download the map on your pc. It shows COMPILING 5,051 SUB-LEVELS (99%)... but is stuck there and wont do anything

## Replication
Upload a Update 8 Experimental map on the interactive map -> edit something -> save the new map

### Actual Result
It stays stuck at 99%

### Expected Result
Map should download without any problems

**Comment by AnthorNet** [comment]
Needs the save ;)

**Comment by brokendruid** [comment]
What do you mean by that?

**Comment by AnthorNet** [comment]
My test save is working, so I'll need your save to test.

**Comment by brokendruid** [comment]
[Update 8.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/12935549/Update.8.zip)

**Comment by brokendruid** [comment]
I tried another save and it worked. But the Update 8 save is the most important one for me. Maybe you know what the Issue is?

**Comment by AnthorNet** [comment]
Fix uploading :)

**Comment by brokendruid** [comment]
thank you sir ;)
