### ISSUE TITLE
Unknown item (black question mark) on map render (minor bug/missing implementation)

### ISSUE THREAD

**Issue by TheEvilGreebo** [AnthorNet/SC-InteractiveMap#313]
# Issue
There's something in the save file that renders as a {?} kind of icon.

## Replication
Load the file here: https://drive.google.com/file/d/1LySZIiFi_n_ByrwmOzr0XuqSEOA7Z35D/view?usp=drive_link

Look at -99k, +182k (southwest portion of map, Snaketree Forest between the lakes

I believe it's Hog Remains - there's one left laying on the ground in that general area.  However, the hog remains are slightly west, under the little platform.  I don't see anything in the exact spot that's marked.

**Comment by AnthorNet** [comment]
That's a map marker, you can remove them from the in-game map or delete it :)

**Comment by TheEvilGreebo** [comment]
Huh.  I didn't think I had any markers but when I looked on the map, there was a grey almost invisible ? symbol.

Sorry about that!
