### ISSUE TITLE
Coordinates displayed in wrong order of magnitude

### ISSUE THREAD

**Issue by kiddikai** [AnthorNet/SC-InteractiveMap#315]
# Issue
World coordinates are displayed in the ingame map as well as in SCIM. However, the numbers are not the same.

## Replication
Locate the uranium node in Rocky Desert in SCIM and the ingame map.

### Actual Result
SCIM says the node is located at -132.772/-187.579.
The ingame map says it is located at -1327/-1875.
The values are off by a factor of 10.

### Expected Result
Both SCIM and the ingame map show the same coordinates (-1327/-1875).

**Comment by AnthorNet** [comment]
SCIM has always shown internal Unreal engine by default, which are in centimeter.  Later the game added coordinates in the map in meters. You can change that in the SCIM map options.

![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/1d8ae096-1415-45f3-9e0e-04cd12f51a60)
