### ISSUE TITLE
vehicles not visible on map, but is visible in stats

### ISSUE THREAD

**Issue by Ryder17z** [AnthorNet/SC-InteractiveMap#317]
# Issue
Vehicles are listed in stats but not visible on the map

## Replication
Load attached save, try to find, i.e. the tractor near the topright corner of the map.
[PIKPIK.sav.txt](https://github.com/AnthorNet/SC-InteractiveMap/files/13624200/PIKPIK.sav.txt)
(remove txt extension)

### Actual Result
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/2000703/c3e8a25a-ef39-40b7-b099-7aae7eefc5d4)

### Expected Result
Visible vehicle icons.

**Comment by AnthorNet** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/4acb87b1-f95b-47ce-ba1f-7cb281402160)

??

**Comment by AnthorNet** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/a822d5e1-f8a2-4b7a-b1af-5df02fc90521)

**Comment by Ryder17z** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/2000703/3a637116-64a6-4a86-9863-2789d7cfaacd)

Maybe it's something specifically happening on Opera GX then

**Comment by AnthorNet** [comment]
Have you enabled icons under map options?
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/06bf8495-8ddf-45c0-b6c6-19d4808bafb6)

**Comment by Ryder17z** [comment]
Seems behavior changed then, because i haven't had to toggle it before. It works as intended
