### ISSUE TITLE
Can't upload save file

### ISSUE THREAD

**Issue by natepaxton** [AnthorNet/SC-InteractiveMap#318]
# Issue
Save files can not be uploaded.  The interactive map gets stuck loading.  Loading the map without a save file takes a very long time.

## Replication
1. Drag save file to upload area.
2. Wait
3. Wait
4. Wait

### Actual Result
None

### Expected Result
The save file should be uploaded and editable

**Comment by AnthorNet** [comment]
Where is your save file?

**Comment by natepaxton** [comment]
In the standard save location on my computer.  This has failed with multiple save files.

**Comment by AnthorNet** [comment]
Should be fixed, but your need to upload your save for specific issues.

**Comment by natepaxton** [comment]
It is fixed.  Thank you!
