### ISSUE TITLE
Deleting railroad tracks causes hang

### ISSUE THREAD

**Issue by crwolff** [AnthorNet/SC-InteractiveMap#319]
# Issue
Deleting a section of railroad track causes an error in the firefox debug, and doggy box popup stays on screen.

> Uncaught TypeError: this.railroadSubSystem is undefined
>     deleteGenericBuilding https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2
>     delete https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2
>     vt https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2
>     callback https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2
>     onEscape https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2
>     processCallback https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2
>     modal https://static.satisfactory-calculator.com/js/InteractiveMap/build/SCIM.js?v=1703768758:2

## Replication
1. Using the rectangle selection tool, select a section of railroad track
2. Choose delete items
3. Click 'no' on the doggy box popup

### Actual Result
Popup stays on screen, track is not deleted (some other items are deleted, presumably depending on priority)

### Expected Result
Track should be deleted, popup should go away

**Comment by AnthorNet** [comment]
Damn, sorry about that one, I'll be sure to fix it in priority when I'm back on January 8th.

**Comment by AnthorNet** [comment]
Fixed :) Deploying
