### ISSUE TITLE
Electrical network breaks after saving save 

### ISSUE THREAD

**Issue by Noobgam** [AnthorNet/SC-InteractiveMap#320]
# Issue
When loading the save from the file produced by interactive map the network seems to be completely broken.
Looks something like this in-game:
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/10178515/60acee75-e725-43d8-b3eb-4fb2b2c7c4df)

## Replication
1. Upload / Download the same save file (or make any changes to it)

### Actual Result
The network seems to be connected when uploaded back to save editor, but in reality is not.

### Expected Result
The saves to be uploadable/downloadable

Save data to check, `last_try.sav` - clean, `last_try_rev` - NOOP import/export from interactive map
[save_data.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/13798829/save_data.zip)

**Comment by AnthorNet** [comment]
Hmmm that's a first! I'll check when I'm back on January 8th.
