### ISSUE TITLE
Feature Request: Apply swatch to all buildings in selection

### ISSUE THREAD

**Issue by Knerten0815** [AnthorNet/SC-InteractiveMap#325]
Would be great for color coding factories

**Comment by AnthorNet** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/6a93a206-f1d1-4e4d-8a75-16729649ef0d)

Already in :)

**Comment by Knerten0815** [comment]
Oooooooooh i actually saw that, but thought it would just update the swatch thats already applied for some reason. I only needed to click submit to see the next menu xD
Thank you sooooo much! That saves so much work for me :D
