### ISSUE TITLE
Some oil wells are not displayed on the map

### ISSUE THREAD

**Issue by Fureyme** [AnthorNet/SC-InteractiveMap#326]
![Снимок экрана 2024-05-27 132646](https://github.com/AnthorNet/SC-InteractiveMap/assets/133177863/aa2d1dd6-8ada-4f96-9ced-71ed92e09fed)

**Comment by AnthorNet** [comment]
Hey, those 4 are nodes, not wells.

**Comment by AnthorNet** [comment]
![image](https://github.com/AnthorNet/SC-InteractiveMap/assets/654353/08cd1306-67d5-4bc5-ba99-0cb00af94529)

**Comment by Fureyme** [comment]
sorry
