### ISSUE TITLE
Hog Research and Spitter Research missing for 1.0

### ISSUE THREAD

**Issue by SabSparrow** [AnthorNet/SC-InteractiveMap#330]
# Issue
The Hog Research and Spitter Research are missing. This causes the research to become locked if the save is downloaded from SCIM. This doesn't seem to be the same as [issue 301](https://github.com/AnthorNet/SC-InteractiveMap/issues/301), because that issue was for update 8, and the issue isn't currently present in the update 8 version of SCIM, maybe it was fixed there?

## Replication
1. Load a game into SCIM, stable branch
2. Click Research, M.A.M., Alien Megafauna
3. Download the save, load into it in-game

### Actual Result
Only 9 schematics are listed in Alien Megafauna in SCIM, the Hog Research and Spitter Research are missing.
Hog Research and Spitter Research are locked in-game after downloading the save.

### Expected Result
11 schematics should be listed, including Hog Research and Spitter Research.
Hog Research and Spitter Research should remain unlocked after downloading a save if they were unlocked originally.

**Comment by AnthorNet** [comment]
Should be fixed interally
