### ISSUE TITLE
Update Game Map to 1.0

### ISSUE THREAD

**Issue by Speedy37** [AnthorNet/SC-InteractiveMap#334]
Current Game Map is not in sync with 1.0

**Comment by AnthorNet** [comment]
You mean man the background?

If yes it is processing :D we use multiple AI software to move from 8k to 32k then smooth it.
Then you have to slice the image for all zoom level into little tiles and upload it :) 

Soon ;)

**Comment by Pysis868** [comment]
@AnthorNet What do you use for your tile work?

**Comment by AnthorNet** [comment]
I've got a modified python script.
Tiles are uploading and will we online tomorrow morning.
Realistic map won't be updated as the Unreal Engine 5 broke our scripts and still unsure if I might be able to fix it.

**Comment by Pysis868** [comment]
Can I see any of those, or are they proprietary / closed source?

**Comment by AnthorNet** [comment]
Map background updated.

@Pysis868 Using a modified version of gdal2tiles

**Comment by Pysis868** [comment]
Ah, I have heard of that.
https://gdal.org/en/latest/programs/gdal2tiles.html
Still curious for your modifications, specific invocation, and the other UE scripts too.
