### ISSUE TITLE
Save downloaded from SCIM no longer has working Chrome/Copper finish

### ISSUE THREAD

**Issue by Thundaknight** [AnthorNet/SC-InteractiveMap#335]
# Issue
After downloading a save from SCIM (Stable branch) and importing it into the game, the copper, chrome and carbon steel finish has changed from the shiny finish to a basic white, orange and grey color. Re-applying the finishes also will not work, as the finish appears to have been changed in the game away from the 1.0 look. 

## Replication
1. Go to SCIM, upload a save from your game
2. Make a change, I had to edit my player inventory due to a crash (added tools)
3. Download the save from SCIM
4. Upload save to game 
5. Color Finishes will no longer work. 

### Actual Result
All finishs change from a shiny finish to a basic color, Chrome = white, Copper = orange/yellow and carbon steel = grey. Without any of the reflective shine. 

### Expected Result
No change to any finishes as they were not adjusted in game.  Image added of what happened after the SCIM save, and what the finishes looked like before.

### Troubleshooting
1. Restored to previous save, and re-uploaded to SCIM
2. Confirmed in SCIM that correct finish was selected on items before downloading
3. Confirmed going back to a previous save shows the correct finish design, ensuring issue is with the save from SCIM.

Look after save:
![scim-issue](https://github.com/user-attachments/assets/7b1052aa-9192-43f6-a3d0-d4cd027067cd)
Look before save:
![scim-before issue](https://github.com/user-attachments/assets/b9a8f63d-4d5c-4779-a1cc-3a4006b8ed1b)

**Comment by AnthorNet** [comment]
Try to refresh, I could not reproduce it this morning, could you send both saves for checking?

**Comment by Thundaknight** [comment]
I've created a new save from SCIM, only edit I did was add a chainsaw and then tested trying to apply a chrome finish. It changed the color of the finish to white immediately.  
SCIM save has the _calculator to the end of the save file.
[SCIM Issue.zip](https://github.com/user-attachments/files/17041426/SCIM.Issue.zip)

**Comment by AnthorNet** [comment]
Deployed potential fix, could you confirm?

**Comment by Thundaknight** [comment]
Didn't work, still seeing the finishes appear incorrectly after creating a new save

Save file I tested:
[SCIM Test.zip](https://github.com/user-attachments/files/17047324/SCIM.Test.zip)

**Comment by AnthorNet** [comment]
Make sure you have emptied your cache?
