### ISSUE TITLE
The live example no longer works

### ISSUE THREAD

**Issue by MartinBlackburn** [AnthorNet/SC-InteractiveMap#336]
# Issue
The link in the read me for the live example map no longer works, due to an old save.

## Replication
1. go to the live example: https://satisfactory-calculator.com/en/interactive-map?url=https://github.com/AnthorNet/SC-InteractiveMap/raw/main/CREATIVE%20TEST.sav
2. see error: That save version isn't supported anymore... Please save it again in the game.

### Expected Result
the map to load with a predefined save.

I would open a pull request, but I don't have any interesting saves, especially not one that would show all the features of the interactive map.

**Comment by AnthorNet** [comment]
Well I need to push all commit, will happen at some point :p
