### ISSUE TITLE
SCIM / Statistics shows incorrect consume / production ratio when using Somersloop 

### ISSUE THREAD

**Issue by JScoff** [AnthorNet/SC-InteractiveMap#337]
# Issue
When using Somersloop to double Production building output, SCIM doubles not only the output, but also required input for production

## Replication
1. As example, build generic production line for Iron Ingots - 1 Mk1 Miner on Impure Node with 30 ore/min output and 1 Smelter with 30 ore/min input and 30 ingots/min output
2. Save the game and load it to SCIM
3. Check SCIM / Statistics page - it should show equal stat for iron ore - 30/min production and 30/min consumption
4. Back to the game, take Somersloop and insert it to the Smelter to double output
5. Save the game and load it to SCIM

### Actual Result
SCIM / Statistics for Iron Ore shows as negative - 30/min production and 60/min consumption

### Expected Result
SCIM / Statistics for Iron Ore shows positive - 30/min production and 30/min consumption, as Somersloop only affects output

**Comment by AnthorNet** [comment]
Fixed
