### ISSUE TITLE
Importing megapring and saving 

### ISSUE THREAD

**Issue by zstephen394** [AnthorNet/SC-InteractiveMap#339]
# Issue
I'm unable to download an altered save file

## Replication
1. I selected a build from my 0.8 world and saved it as a megaprint.
2. Uploaded my current 1.0 world save to the interactive map.
3. Import and place in the original location the magaprint saved from 0.8.
4. Go to Save the World save to add back to the game, and saving stops at 81%

### Actual Result
Saving stops at 81%

### Expected Result
I want to have a world save file to add back into my satisfactory game files. (My assumption is that the issue is taking a build from .08 and bringing it to 1.0. Hopefully, this is still doable.

**Comment by AnthorNet** [comment]
It would be easier if you provided the megaprint and the saves.

**Comment by Itsotso** [comment]
I'm trying to do the same thing and it gets stuck at 61% trying to compile the files.
[Save.zip](https://github.com/user-attachments/files/17083595/Save.zip)

**Comment by AnthorNet** [comment]
Fixed :)
