### ISSUE TITLE
Limestone Node - Wrong Purity Listed

### ISSUE THREAD

**Issue by thedoctorjtd** [AnthorNet/SC-InteractiveMap#341]
# Issue
The limestone node in the below image is a `normal` node, not `pure`. 
Coordinates 66,757 / -150,677
Persistent_Level:PersistentLevel.BP_ResourceNode464_UAID_40B076DF2F790FE201_1577140465

![image](https://github.com/user-attachments/assets/1516e34d-5571-44de-806a-8960f4c742d5)
![image](https://github.com/user-attachments/assets/4fc25168-4fda-44a8-90cf-1a946904cf41)

## Replication
n/a

### Actual Result
n/a

### Expected Result
Update map. :)

**Comment by AnthorNet** [comment]
Fixed internally, will deploy today
