### ISSUE TITLE
Ability to reset all Collectible counts.

### ISSUE THREAD

**Issue by TheSkunkMonkey** [AnthorNet/SC-InteractiveMap#344]
Have been getting a lot of requests for the ability to reset the counts on all collectible as well as hard drives. Sloops, Mercs, and Slugs specifically. Individual reset buttons would be nice as well.

**Comment by houghi** [comment]
It would be nice if the ability to set it to zero as well, just like with e.g. hard drives. Or perhaps this is already being implemented.

**Comment by AnthorNet** [comment]
Under Options > Collectable
Not that this only works for visited areas ;) And the rest will follow once I get the new format working properly

**Comment by YokujinKaze** [comment]
will you also add the ability to reset other resources?
ore deposits, all sorts of flora (such as trees, roots, bushes, grasses, blue mushrooms, mycelia, etc) and other harvestable resources that never regrow
and the plants of beryl berry and paleberry if those got destroyed

while not collectibles: reset gas pillars and spore flowers

**Comment by YokujinKaze** [comment]
edited and added more suggestions in my previous post
