### ISSUE TITLE
Error when deleting a certain conveyor lift

### ISSUE THREAD

**Issue by Tremolo4** [AnthorNet/SC-InteractiveMap#345]
# Issue
Error when attempting to delete a certain conveyor lift.
*Note*: Deleting this lift in-game also crashes the game. I'm hoping to be able to delete it in SCIM to prevent our game from crashing.

This issue came about as a player was working with blueprints on our dedicated server. Their game crashed a few times and eventually the server crashed as well. Something about this lift is seriously broken in this blueprint and its placed instance(s).

*EDIT: Second Note*: Game performance in this savegame is also abysmal (low FPS) until you load it into SCIM and download again without actually changing anything. This started happening around the same time as the crashes.

## Replication
1. Load this savegame: [ConveyorLiftCrash.zip](https://github.com/user-attachments/files/17196662/ConveyorLiftCrash.zip)
2. Delete one of the Conveyor Lifts marked in this Screenshot: ![SCIM_error](https://github.com/user-attachments/assets/8302902f-e777-46a9-bd69-197b1dbca1c9)

### Actual Result
The lift is still there and an error occurs in SCIM.

### Expected Result
The lift to be deleted fully even in this broken state in order to hopefully resolve the in-game crash as well.

**Comment by Tremolo4** [comment]
So after posting this issue I went at another round of trying to fix my savegame and seem to have found a way!

The conveyor lifts can not be deleted in the game or SCIM due to crashes (the point of this issue). However, the mergers and splitters connected to these lifts can be deleted in SCIM at least (not the game). After deleting all mergers, splitters, smelters and constructors that can be seen in the screenshot via SCIM, I was then able to delete everything else, including the conveyor lifts and the blueprint designer in the game without it crashing. (Note there are multiple stacked on top of each other (expected), and even inside of each other (weird blueprint bug)).

So, thanks SCIM <3

**Comment by AnthorNet** [comment]
Please try to refresh your cache, that issue was fixed and I cannot reproduce it anymore :)
