### ISSUE TITLE
Priority Power Switch is not a filterable object

### ISSUE THREAD

**Issue by Housepartyy** [AnthorNet/SC-InteractiveMap#347]
# Issue
You cannot filter buildables by priority power switch. I noticed because I have a couple I need to delete and I have no idea where they are as they do not connect power networks but are only connected on one side. 

## Replication
1. Try to filter by priority power switches on SCIM

### Actual Result
You cannot.

### Expected Result
You are able to so you can spot the switches on the map.

**Comment by AnthorNet** [comment]
Switched Power Lines to Power Utilities
Deployed a bit later ;)
