### ISSUE TITLE
Feature request: native ability to use the map renderer to create GIFs

### ISSUE THREAD

**Issue by SignpostMarv** [AnthorNet/SC-InteractiveMap#35]
Making them by hand is cumbersome, not only because of manual effort but also due to #33 and #34 

Multiple file uploads, with user-entered frame delay per file would be most useful.

For reference, see attached gif (manually created GIMP file available on request).
![v13 - 20210118-0224 to 20210131-0337](https://user-images.githubusercontent.com/304403/106378401-637b3900-639c-11eb-93f5-cea33f2fc849.gif)

**Comment by elpaulo** [comment]
I would love to have this !

**Comment by SignpostMarv** [comment]
After having played a single session for over 150 hours, saving at each stage relevant to show progress I'm of the conclusion that this feature request might not be ideal for integrating with the website itself, but with a separate project using headless chrome to facilitate it as a commandline tool.

tl:dr; I don't imagine Anthor wants to support users being able to drop 717 files onto the website and expecting it not to fall over when compiling gifs.

**Comment by AnthorNet** [comment]
Might be a little bit out of scope :)
