### ISSUE TITLE
Industrial Rail on ramps doesn't display image

### ISSUE THREAD

**Issue by robcole-dev** [AnthorNet/SC-InteractiveMap#350]
# Issue
When on the Interactive map the Industrial Rail isn't displayed correctly
![image](https://github.com/user-attachments/assets/6692994b-637b-483b-a909-39144835c7dc)

## Replication
1. Load map that has industrial Rails placed

### Actual Result
When hovering over the item only a block ID is given

### Expected Result
I would exect it to act like other blocks and display it's name and an image.

**Comment by AnthorNet** [comment]
I believe this one is fixed but not pushed yet.
Will be today ^^
