### ISSUE TITLE
Uranium resource deposits display as SAM on map

### ISSUE THREAD

**Issue by TunezNZ** [AnthorNet/SC-InteractiveMap#351]
# Issue
When resource deposit layer is turned on, the nodes identified as SAM are observed to be uranium nodes in the game.

## Replication
An example is at coordinates 34,211 / 15,276 the 6 nodes are mapped as SAM, but are uranium in the game

### Expected Result
Should be correctly displayed as uranium on the map

**Comment by AnthorNet** [comment]
Deploying soon
