### ISSUE TITLE
Pasted items are rotated by 20°

### ISSUE THREAD

**Issue by effleurager** [AnthorNet/SC-InteractiveMap#356]
# Issue
When pasting an item on top of another, the rotation of the original is not preserved. For some reason, this is off by 20° clockwise from the item below.

## Replication
1. Load a save with a foundation piece
2. Select the foundation piece
3. Copy the selection
4. Paste the selection, specifying it to be pasted on top

### Actual Result
Rotation of pasted item does not match the original below. (E.g.: the centre foundation piece)
![image](https://github.com/user-attachments/assets/bff2c474-67bd-4fab-883b-141271fc7995)

### Expected Result
The pasted item should match the rotation of the item below it.

**Comment by AnthorNet** [comment]
Pasted angle rotation takes into account the foundation rotation you're pasting on ;)
If you want the same angle paste on a foundation fully oriented north.

**Comment by effleurager** [comment]
I can understand one might use that to rotate things progressively, but I can't imagine that being a default expectation – every 3D editor maintains the same orientation as the source object. This seems more like a mode option, or _paste special_?
