### ISSUE TITLE
mycelia tracking

### ISSUE THREAD

**Issue by YokujinKaze** [AnthorNet/SC-InteractiveMap#363]
some way to display the locations of mycelia sources in collectibles/items

**Comment by AnthorNet** [comment]
What do you mean by mycelia sources?

**Comment by YokujinKaze** [comment]
mushrooms? like trees/grass but for mushrooms/mycelia?

**Comment by AnthorNet** [comment]
I don't see anything beside bacon agaric?

**Comment by YokujinKaze** [comment]
https://satisfactory.wiki.gg/wiki/Mycelia

**Comment by AnthorNet** [comment]
Those aren't available in save before being destroyed like foliage.
