### ISSUE TITLE
Map changes (Again)

### ISSUE THREAD

**Issue by mingl0280** [AnthorNet/SC-InteractiveMap#368]
New border changes at the west and north of the map.
![图片](https://github.com/user-attachments/assets/4bdcd540-0cb3-4a99-a992-29cde617c38b)

![图片](https://github.com/user-attachments/assets/77a28623-270f-486d-bef0-cffd4132570a)
Note for image 2: P1 is the one on the left, and P2 is the one near the north top.
* All other turning points are unchanged.

**Comment by AnthorNet** [comment]
Fixed internally, next update should be around 15PM UTC.
