### ISSUE TITLE
Don't show all the layers upon file load

### ISSUE THREAD

**Issue by meza** [AnthorNet/SC-InteractiveMap#37]
Hi,

When loading a big save file just to be able to do a quick task in SCIM it always goes like this:

1. open the file
2. go for a coffee
3. fight with a lagging browser to turn off all layers
4. turn off all buildings
5. turn on the only things that I'm interested in

Instead it would be very nice if the layers would be hidden by default. It's very rare that people are interested in _all of it_ when they're loading their own saves. It's more likely that they're interested in a specific thing. It would be a better experience to turn on the one thing instead of turning off everything else.

**Comment by AnthorNet** [comment]
![image](https://user-images.githubusercontent.com/654353/111764390-717d0e80-88a3-11eb-9b8e-107b8b9f0af5.png)

Under map options

**Comment by meza** [comment]
But isn't this something you'd want to set _before_ uploading the map? 
Or is this something you need to do once and the site will remember?

**Comment by meza** [comment]
Is it possible to add a toggle for this button too?

This is the most important one. It's what generates most of the visual noise.

![image](https://user-images.githubusercontent.com/211977/111852157-d705e500-890d-11eb-9022-9c77e20903d0.png)

**Comment by AnthorNet** [comment]
Yeah the options are saved.
For map'layers I'll add something to remember the state too
