### ISSUE TITLE
Dropdown menues for inventory editing breaks when loading a save with mods

### ISSUE THREAD

**Issue by Giomin** [AnthorNet/SC-InteractiveMap#372]
# Issue
The drop down menus for filling or editing inventory slots wont open when the mod has or had mods loaded

## Replication
1. load a save with mods.
2. go and try to edit for example player inventory
3. select the drop down menu for one of the inventory slots

### Actual Result
the menu to select the item wont open

### Expected Result
the drop down menu

**Comment by AnthorNet** [comment]
Needs of save for testing/fixing

**Comment by AnthorNet** [comment]
Will reopen if you send a faulty save to reproduce.
