### ISSUE TITLE
See Radar Tower Range on map

### ISSUE THREAD

**Issue by erinic04** [AnthorNet/SC-InteractiveMap#376]
I would appreciate it if it was possible to see the range of any selected radar towers on the map, as I am going around with them in game trying to collect everything in the ranges of them, and I find it a lot more fun to do this in game, but when deciding where I want to put the next tower or finding the last few slugs in an area, I would find it helpful to be able to see the range of the radar tower on the map, because I want to find all the things in game, but for the last few in a range its helpful to be able to look at the map for them. It would make this process and also trying out different tower placements a lot easier as I can check whether the tower is in a good place to get all the collectibles in an area.

**Comment by AnthorNet** [comment]
Did you tried to hover the radar tower? Circle should appear.

**Comment by erinic04** [comment]
It doesn't appear for me, not on the interactive map like it does in game

**Comment by AnthorNet** [comment]
![image](https://github.com/user-attachments/assets/017b3659-c8eb-48af-a2d3-4cf90c7e7d6f)

**Comment by erinic04** [comment]
![image](https://github.com/user-attachments/assets/b4a374f8-1f0c-4e4a-b857-2b1222bb1f82)

**Comment by erinic04** [comment]
It highlights the entire map in orange

**Comment by AnthorNet** [comment]
Did you zoom out while hovering the radar tower?

**Comment by erinic04** [comment]
Yeah I did zoom out while hovering on it, otherwise it's too small and crowded around to select

**Comment by AnthorNet** [comment]
Yeah that should be fixed then ;)
