### ISSUE TITLE
Bug Related To Searching Blueprints and Megaprints

### ISSUE THREAD

**Issue by Darkestry** [AnthorNet/SC-InteractiveMap#378]
# Issue
When searching for blueprints or megaprints, it is not showing related posts.

## Replication
If I type in power storage for instance, I get no blueprints related to that, although there are in fact multiple blueprints having "power storage" in their title when going through all the blueprint pages manually.

### Actual Result
The default search is applied. No indexing happens.

### Expected Result
A list of all blueprints related to the keyword "power storage".

**Comment by AnthorNet** [comment]
the search is looking for the words in both title and description.
IF you quote: "power storage" is will return both words together, if you search without quote it will return either power or storage
