### ISSUE TITLE
stuck while compiling

### ISSUE THREAD

**Issue by MrGameVideos** [AnthorNet/SC-InteractiveMap#38]
When I export my map to an savefile it won´t finish and stays at "compiling 0 collectibles"
This has been an issue with 2 saves, one of them newly generated without doing anything.
And I found out this is only an issue in chrome. It works perfectly in edge.
Here´s my modlist:
![Unbenannt](https://user-images.githubusercontent.com/79053996/107882816-ca940400-6eeb-11eb-881a-2b778c38db9b.PNG)

**Comment by AnthorNet** [comment]
Please send your save

**Comment by MrGameVideos** [comment]
> Please send your save

https://uploadhub.to/c8b1f90894335fa27a3fe1779b97e1b8/Hello.sav
https://uploadhub.to/2e44434cf7157f93aa72b905e6695d9f/Racetrack.sav

**Comment by AnthorNet** [comment]
I could not reproduce it using Chrome, could you check the browser console and send me the error?

**Comment by MrGameVideos** [comment]
> I could not reproduce it using Chrome, could you check the browser console and send me the error?

**Comment by MrGameVideos** [comment]
![Unbenannt](https://user-images.githubusercontent.com/79053996/108987428-8d6e0580-7693-11eb-8235-bc67a26fa82b.PNG)
You mean this?

**Comment by AnthorNet** [comment]
Yes but while saving, current output didn't show the save part
