### ISSUE TITLE
Blueprint position not updated when using 'Offset Selected Items Position'

### ISSUE THREAD

**Issue by sendit2ash** [AnthorNet/SC-InteractiveMap#380]
# Issue
When using the rectangle selection tool and then option 'Offset Selected Items Position' to move objects, the origin of the blueprint is not moved with the items causing snapping issues with blueprints when using the modified save.
Under advanced debug the 'transform' value for "PersistentLevel.FGBlueprintProxy" remains the same after moving the items.

## Replication
1. Build a blueprint
2. Snap another blueprint to the side of the blueprint
3. Save
4. Edit save, selecting the blueprints you created with rectangle selection tool
5. Choose "Offset Selected Items Position" and offset by some distance (e.g. x+3200)
6. Save modified file
7. Load file into Satisfactory, snap a third blueprint to the side of the existing two blueprints

### Actual Result
The third blueprint will snap to the original position of the blueprints prior to the objects being moved

### Expected Result
The third blueprint should snap to the updated position of the blueprints

**Comment by JurrijnP** [comment]
This bug also happens when using the 'Move Selected items position' option and is pretty annoying as it prevents you to move anything that was built with a blueprint
