### ISSUE TITLE
Differentiate belts and vechicle paths

### ISSUE THREAD

**Issue by Bilge** [AnthorNet/SC-InteractiveMap#381]
Incredible tool, but I cannot help but wonder if the belt colour could be changed so as not to be the same as vehicle paths? One is solid and the other is dashed, but that alone does not make them easy enough to distinguish.

![image](https://github.com/user-attachments/assets/eb3a2b7b-d5a1-49a1-a07a-8624607886b4)

**Comment by AnthorNet** [comment]
Better?

**Comment by Bilge** [comment]
In the sense that I can now differentiate between tracks and belts, yes, although I find this particular combination of purple on brown to still be particularly difficult to see. I would suggest bumping up the purple hue's lightness and/or desaturating it somewhat to make it easier on the eyes.

![image](https://github.com/user-attachments/assets/cb6f54ed-fb5c-4e40-89ff-34498f0d7ca6)

**Comment by Bilge** [comment]
Looks fine now. Not sure why it appeared brighter before.

![image](https://github.com/user-attachments/assets/ba184d42-ede2-48ae-9da2-24a7945eeb37)
