### ISSUE TITLE
Raw Quartz Nodes Missing x3

### ISSUE THREAD

**Issue by Faun666** [AnthorNet/SC-InteractiveMap#382]
x3 Locations of Raw Quartz Nodes missing from the map even with all filters on.

All nodes are near the following coordinates:

X: 55253.2578125
Y: 205856.15625
Z: -5718.9716796875

Just something I noticed when looking around the interactive map.

**Comment by AnthorNet** [comment]
![image](https://github.com/user-attachments/assets/b3541965-80ba-4925-830b-a0ac5b414c22)

Are you sure to be on Stable branch?
