### ISSUE TITLE
Placed Blue Print Ghost

### ISSUE THREAD

**Issue by DavekeC** [AnthorNet/SC-InteractiveMap#385]
After Mass dismanteling trough use of the interactive map it seems like the outlines of the blueprints remain in place.
They are now empty so can't be delented with the building gun either.

## Replication
Build Blue print , remove with map planner

### Actual Result
The blueprint outline is still there

### Expected Result
The blueprint outline to be deleted along with the buildings.

**Comment by AnthorNet** [comment]
CAn I get the faulty save please?
