### ISSUE TITLE
SCIM fault with adjusting machine clock speeds with area select tool. 

### ISSUE THREAD

**Issue by AKSNZ-ASH** [AnthorNet/SC-InteractiveMap#387]
# Issue
*describe the issue*

## Replication
1. list some replication steps

### Actual Result
*describe what happens following the replication steps*

### Expected Result
*describe what you expect to happen instead of the bug you described*

**Comment by AKSNZ-ASH** [comment]
Issue
After area selecting a group of machines (fuel generators) and using the area selection menu I have tried to adjust the clock speed of the selected machines from default 100% to 240%. I have toggled on the option for using power shards from containers.

After saving the file and loading it into satisfactory the machines are still on 100% and have not applied any power shards.

Sufficient shards have been available in both storage containers and personal inventory. 

list some replication steps:
1 - place a group of machines.
2 - fill a container of power shards.
3 - upload save to SCIM
4 - area select machines.
5 - adjust machine clockspeeds via selection tool menu to 240% and toggle on 'use powershards from containers.'
6 - save edited file.
7 - load edited file in game.
8 - check machine clock speeds in game (should be 240%).
9 - realize machine clock speeds are still 100% and shardless.
![image](https://github.com/user-attachments/assets/538131cf-4140-4ab1-843a-92cc6aceb86c)
10 - scratch head. 

Expectation:
After completing steps 1 to 8 = machines should be clocked at the adjusted rate with shards.

Cheers, AKSNZ

**Comment by AnthorNet** [comment]
Could you share the save and make sure you have refreshed your cache?
I could not replicate the issue.

**Comment by AKSNZ-ASH** [comment]
Hi Anthor,

Sorry but the save file has probably been over written a bunch of times
since the time of posting. I was able to area clock machines once I used
shards generated within the game using advanced game settings. I believe
the issue came from shards spawned using SCIM. I started with empty
generators (no shards) used the SCIM to fill containers of shards and tried
to area clock the machines using the SCIM-spawned shards which also
interestingly couldn't be deleted out of my inventory in-game either.
Probably buggy shards rather than the area clocking tool. Could you try
fill containers / inventory with shards through SCIM and see if those will
delete in-game?

Cheers,
ASKNZ

**Comment by AnthorNet** [comment]
I think it should be ok now :)
