### ISSUE TITLE
Changing Color Swatch Slot for selected objects does not work

### ISSUE THREAD

**Issue by th-m-vogel** [AnthorNet/SC-InteractiveMap#388]
# Issue
Changing Color Swatch Slot for selected objects does not work

## Replication
1. Select an area (rect, circle, lasso does not matter)
2. Select "Update selected buildins color slots"
3. chose the swatch you want
4. download save game

### Actual Result
load the save, check in game, somewting different is assigned. To my diagnostics is even looks like ther was no swatch slot assigned to the objects, just some colors that not even match any of my swatches.

For what i tested (and also actually need) it was all foundations.

### Expected Result
well yes, the swatch i selected is applied to the objects.

**Comment by AnthorNet** [comment]
![Uploading image.png…]()
Made a quick test and I could not reproducie it.

**Comment by th-m-vogel** [comment]
![Screenshot20241120-17262400000](https://github.com/user-attachments/assets/a667f34c-4a8a-43de-81f7-6198931010d2)

Upper Block, all 18 swatches set by interactive map, click on foundation and update swatch, right block of 9 identical foundations, marked by lasso tool and updated to swatch 18

Lower Block, in game applied all 18 swatches, right block of 9 identical foundations, marked by lasso tool in interactive map and updated to swatch 18.

My swatches 1 to15 are unchanged, i only customized 16, 17 and 18. And exactly those swatches come out to something different than defined in game. Also, changing to swatch 18 is different in individual update and mass update. 

What i also noticed, only my custome swatch is represented in interactive map right color. the other 3 customized swatches are something totally different when in interactive map and they are also different in the swatch chooser for individual / mass update.

What i also need to mention, my Swatches 16 to 18 are extended color range (luminosity greater 1) as you can see in the hand pained referance block.

**Comment by AnthorNet** [comment]
Link that save please

**Comment by th-m-vogel** [comment]
Attention, very modded ... but no swatch / color related mods. 
[A New World.zip](https://github.com/user-attachments/files/17838041/A.New.World.zip)

**Comment by th-m-vogel** [comment]
Little update on this, it works on swatches within the normal color range (RGB). I changed on of my unused swaches, and everything is fine. Single foundation update and mass update. it happens only for "extreme colors" where saturation or luminosity is outside of the 0 to 1 range. However, that's what you need for ceramic white and pichtch black foundations (and other colors).

What i also noticed, foundations updated to swatches having those types of colors using interactive map are in game not even recognized as foundations having a swatch applied. They are just colored foundations. When you want to apply a swatch to them non is gives the indicator "swatch already applied"

**Comment by th-m-vogel** [comment]
Realized file attach did not work 1st time, updated, now it is downloadable.

**Comment by AnthorNet** [comment]
I see normalisation might be in the code, I'll check it

**Comment by AnthorNet** [comment]
Not sure that fix everything, but at least the subsystem holding the color slot should be found correctly!

**Comment by th-m-vogel** [comment]
It works now, somewhat. I'm still testing. Positive for now, it works for swatches with normal colors. And that gives me already a workaround for my actual use case. 
What i can't finally conclude, there is either a special problem with swatch 17 and 18 or with any swatch in the list that has a place "behind" a swatch with a special color assigned. I will try to find out. 
When it does not work, it assigns "Concrete Structure Swatch" instead.

**Comment by th-m-vogel** [comment]
I created a fresh game, all swatches untouced. It works, but not for swatch 16,17 and 18. I think i found a very specific case by using this swatches for my special color swatches ;) 

Attached my exported game. You will find there only a single and a double row of 2m foundations. The single row has color swaches 1 to 18 applied by interactive map (from left to right, right is where to original colored foundation is located.

You will see, foundation 16,17,and 18 have a (the same) color applied, but it is none of the swatches (including ficsit swaches and metallic swatches)

In scim it all looks correct but not in game. Then i saved the game and loaded the save to scim. the 3 foundations disapeared in scim (se second attached save file), however, they still exist in game when reloading the save.

The double row was ment to test with bulk update, but i stopped here as i found this issue already with single update.

Hm, 1 to 15 OK and not more  ... fells like something that is byte size and runs out of range ... 

[Test World_CALCULATOR.zip](https://github.com/user-attachments/files/17952336/Test.World_CALCULATOR.zip)
[Test World_Calculator saved from game.zip](https://github.com/user-attachments/files/17952373/Test.World_Calculator.saved.from.game.zip)

**Comment by th-m-vogel** [comment]
I can also confirm, extrem colors (saturation / luminosity greate that 1) work with scim, as long as they are not assigned to swatch 16 to 18.

In addition: set foundations to swatch 16 to 18 in scim, save in scim, load in game, save in game, load to scim, those foundations are gone in scim, save again in scim and now load in game, foundations also gone in game.
