### ISSUE TITLE
Toggle to hide collected Slugs/Spheres/Sloops from map

### ISSUE THREAD

**Issue by tpill90** [AnthorNet/SC-InteractiveMap#389]
When I'm using the map to find Slugs/Spheres/Sloops that I haven't collected yet,  I find it distracting to have the transparent shadow icon marking where previously collected items were.  I would like to ask that there be a toggle to hide them all together from the map, leaving only non-collected items visible.

![Untitled](https://github.com/user-attachments/assets/dc004260-4d3a-4169-8f1e-ab9c2953292a)

**Comment by tpill90** [comment]
Tested with the Update 8 version of the map.  Looks like the `Show collected icons?` toggle is working correctly in that version 
![image](https://github.com/user-attachments/assets/9b55d94f-df88-41d8-a6f3-8a27d2db26d7)

Save file I used: [Aaron Server_131024-122326.zip](https://github.com/user-attachments/files/17666450/Aaron.Server_131024-122326.zip)

**Comment by tpill90** [comment]
I tried clearing my browser cache just now, and the icons are working as expected.  From looking through the code it looks like maybe there was an invalid value being stored in `local storage`?

**Comment by AnthorNet** [comment]
Most likely something that got fixed ^^
