### ISSUE TITLE
Missing cave in Dangle Spires biome

### ISSUE THREAD

**Issue by yiip87** [AnthorNet/SC-InteractiveMap#39]
Hi,
I went on a Power Slug hunt and noticed a missing cave in the Dangle Spires biome.
The cave is located as shown in this screenshot:
![Screenshot 2021-03-03 024505](https://user-images.githubusercontent.com/4689824/109741203-e1657680-7bcc-11eb-910b-38cb515c0bd2.png)

Would it be possible to add this cave in a future version?

**Comment by AnthorNet** [comment]
Yes you can map caves with beacons all around, provide me the save and it will be added :)

**Comment by yiip87** [comment]
There you go :)
[Dangle-Spires-Cave.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/6079212/Dangle-Spires-Cave.zip)

**Comment by AnthorNet** [comment]
Added :) Will show on next production push
