### ISSUE TITLE
Add a Megaprint button is not showing.

### ISSUE THREAD

**Issue by 69of1337** [AnthorNet/SC-InteractiveMap#395]
# Issue
"Add a Megaprint" green button in the blueprints is not showing.
Add a Blueprint is present and works fine.
the my blueprint menu from the account drop down menu works only for blueprints, I am unable to upload .cbp files.

## Replication
tried re-logging and in different browsers

### Actual Result
Same result 
![nomegaprint](https://github.com/user-attachments/assets/06a7481d-e3fc-4a6a-a8a9-6764152281dc)

### Expected Result
I just want to add a megaprint to the satisfactory megaprint library.

**Comment by AnthorNet** [comment]
DM me on Discord to get your account approved
