### ISSUE TITLE
Undefined Source. Probably Fiscit Networt MOD

### ISSUE THREAD

**Issue by Life78** [AnthorNet/SC-InteractiveMap#397]
# Issue
while Loading Safe File, there is an undefined source error

Is it possible, just to leave undefined sources out, and continue with defined sources?
[LG.zip](https://github.com/user-attachments/files/17900581/LG.zip)

**Comment by AnthorNet** [comment]
No, need a proper parsing

**Comment by AnthorNet** [comment]
Should be fixed, may be partially, but had 2 save working with the current fix
