### ISSUE TITLE
Hostile advertisers have too much free reign on page. Borders and click handlers getting override.

### ISSUE THREAD

**Issue by whiskeyfur** [AnthorNet/SC-InteractiveMap#398]
# Issue
![image](https://github.com/user-attachments/assets/e2bc3a4f-e852-4013-abc6-5a716b925202)
Advertisers keep causing the bottom border to jump higher and end up covering the bottom of the map. 4 times now I've clicked on an add instead of an ore node.  Not acceptable.

One advertiser had already overwritten the click handler of the entire page to make the map completely useless and just an advert.

## Replication
1. Load the site
2. watch the ads make the bottom border bounce
3. On occasion (unknown which advertiser), an advert will override the click handler for the entire page and render the map useless.

### Actual Result
Page redirected to the advertiser's website.

### Expected Result
UNOBTRUSIVE ads that do not radically change the borders of the page nor override the click handlers. This is an accessibility issue as well.

### Possible countermeasure
Set the CORS headers on the page to start disallowing certain behaviors from third party javascript libraries, particularly from https://ad-delivery.net/, https://hb.vntsm.com/ and https://hb-vntsm-com.global.ssl.fastly.net/

**Comment by AnthorNet** [comment]
Sent an email and it should be fixed
