### ISSUE TITLE
Upload save game broken

### ISSUE THREAD

**Issue by kalivra** [AnthorNet/SC-InteractiveMap#399]
Can no longer upload save games to map starting yesterday 29th November 2024.

## Replication
Click on "Click drop your save game here". Select a save game. Upload starts. Task bar gets to "Loading detailed models" and stops.

Have tried several old saves including from a few weeks back with same issue.

Firefox 133.0 (64 bit) for Ubuntu

**Console message**
Loading failed for the <script> with source “https://hb.vntsm.com/v4/live/vms/sites/satisfactory-calculator.com/index.js”. [interactive-map:70:113](https://satisfactory-calculator.com/en/interactive-map)
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [interactive-map](https://satisfactory-calculator.com/en/interactive-map)
Cookie warnings 4
Google Analytics and Tag Manager is being shimmed by Firefox. See https://bugzilla.mozilla.org/show_bug.cgi?id=1713687 for details. sandbox eval code:1:9
Object { saveHeaderType: 13, saveVersion: 46, buildVersion: 382498, mapName: "Persistent_Level", mapOptions: "?ClientIdentity=21000000366337666664653134376166336334366339656631653838306463303039646200010000000608000000160c9c4c01001001?SessionDefinition=SessionDef_SinglePlayer", sessionName: "Grassy fields Solo", playDurationSeconds: 283278, saveDateTime: 638684589392120000, sessionVisibility: 32, fEditorObjectVersion: 40, … }
SCIM.js:2:963252
Inflated: 197 chunks... Read.js:1:56319
Loading 17394 objects... Read.js:1:58059
Loaded 17394 objects...: 80.53ms - timer ended Read.js:1:58850
Loading 17394 entities... Read.js:1:59448
Loaded 6521 lightweight objects... Read.js:1:70089
Loaded 17394 entities...: 661.13ms - timer ended Read.js:1:60718
loadSave: 1233ms - timer ended
**end console**

On one attempt had a message that said something like "unbalanced tree" but I did not write down the exact message or get it to repeat.

### Actual Result
Can no longer use map with save game data.

### Expected Result
Expected data to be parsed and displayed on map.

**Comment by AnthorNet** [comment]
Send the save file!

**Comment by kalivra** [comment]
Two save games. Neither work. One is from October, and one from December.

[October 2024.zip](https://github.com/user-attachments/files/17970253/October.2024.zip)

[December 2024.zip](https://github.com/user-attachments/files/17970254/December.2024.zip)

**Comment by AnthorNet** [comment]
Tested and working on my side, may be you're blocking too much scripts?

**Comment by kalivra** [comment]
It is working this morning for me with no changes. Perhaps related to Ficsmas? Whatever the reason it is working now so bug closed.

Thanks for looking into it.
