### ISSUE TITLE
Missing Cave in Northern Forest

### ISSUE THREAD

**Issue by RhinoRhys** [AnthorNet/SC-InteractiveMap#40]
There is a small cave located near the 6 pure iron nodes within the Northern Forest Biome. The entrance can be found just below the base of the large stone arch by looking for the blue Mycelia and turning left (at roughly 75000,-77000) and IIRC there was a Somersloop inside, but I grabbed it ages ago so cannot be sure.

**Comment by AnthorNet** [comment]
Yes you can map caves with beacons all around, provide me the save and it will be added :)

**Comment by AnthorNet** [comment]
Yes you can map caves with beacons all around, provide me the save and it will be added :)

**Comment by RhinoRhys** [comment]
[cavemap - CALCULATOR.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/6079790/cavemap.-.CALCULATOR.zip)
Very handy that I can give myself lots of beacons using the map :)

**Comment by AnthorNet** [comment]
Should be added ;)
