### ISSUE TITLE
cant upload saves

### ISSUE THREAD

**Issue by Zelleonix** [AnthorNet/SC-InteractiveMap#401]
When i try to upload my .sav file it always says: That save version isn't supported! Are you sure this is a proper save file???
I have tried it multiple times on Different browsers with different save files all of them are supported Versions i dont know what to do.

To replicate it i just tried it on Opera GX Microsoft Edge and on google chrome on my phone
![image](https://github.com/user-attachments/assets/1ced7792-e158-4ea4-b51c-c6a7cd623557)

**Comment by AnthorNet** [comment]
Send the file!

**Comment by Zelleonix** [comment]
> Send the file!

https://drive.google.com/file/d/1_1V7I4ZBaDFL184omGf7WmI7AL-Y2Ed7/view?usp=drivesdk

**Comment by AnthorNet** [comment]
The ServerSettings file is not a save file, it just holds server settings.
