### ISSUE TITLE
Pre-1.0 SAV file that parsed since 1.0 release no longer parses

### ISSUE THREAD

**Issue by dazimmermann** [AnthorNet/SC-InteractiveMap#406]
# Issue
Attaching a modded save file that used to parse in SCIM, but now runs into a parsing issue. File unchange since last successful upload and parse.

## Replication
Upload file to SCIM.  Inflating works, but error on parsing.

### Actual Result
At 99% of parsing 311790 entities, SCIM reports" Something went wrong while we were trying to parse your save game...  Source: undefined. 

### Expected Result
Save loads to map.  Allows megaprint export.
[U8EA-Copiron.zip](https://github.com/user-attachments/files/18087012/U8EA-Copiron.zip)

**Comment by AnthorNet** [comment]
Fixed
