### ISSUE TITLE
Error Parsing Save - Source: readProperty

### ISSUE THREAD

**Issue by TheRealBeef** [AnthorNet/SC-InteractiveMap#407]
# Issue
Save file doesn't load properly in SCIM.

[ErrorRoadPropertySave.zip](https://github.com/user-attachments/files/18141106/ErrorRoadPropertySave.zip)

```
Something went wrong while we were trying to parse your save game...
Please try to contact us on Twitter or Discord!
Source: readProperty
```

I wish I could provide more information as to the error but it's not available for me.

## Replication
Upload attached save file to SCIM.

### Actual Result
It will fail at some point in parsing and provide the above error.

### Expected Result
For the save file to parse properly.

**Comment by AnthorNet** [comment]
Fixed
