### ISSUE TITLE
S.A.M. Ore to be renamed SAM.

### ISSUE THREAD

**Issue by ehoffman2** [AnthorNet/SC-InteractiveMap#408]
# Issue
In 1.0 (Stable) branch, the "S.A.M. Ore" should be renamed "SAM".

## Replication
- There are a few references in main UI under resource nodes tab, when hoovering over the resource (in main UI and in the info card that appear when hoovering over a node on the map).
- It appears to be "fixed" in the production planner, game resource and game progression section.

### Actual Result
Still some references to "S.A.M. Ore"

### Expected Result
As Snutt said, "It's just SAM"!

**Comment by AnthorNet** [comment]
Should be better :)

**Comment by ehoffman2** [comment]
Verified the right pane now display "SAM" in stable branch (and properly displays "S.A.M. Ore" in Update 8 branch).
However, when hoovering over a SAM node on the map, the info card still displays "S.A.M. Ore" in stable branch.  Just a small oops :-)
Please re-open
Thank you!

**Comment by ehoffman2** [comment]
Just verified and now it's correct.  I did clear cache this morning and it was still displaying "S.A.M. Ore".  Now it's displaying "SAM".

Thank you :-)
