### ISSUE TITLE
Feature request: 'Scenic Location' popups

### ISSUE THREAD

**Issue by budak7273** [AnthorNet/SC-InteractiveMap#41]
I think it would be cool to have a layer of markers at particularly cool-looking locations on the map. Perhaps when clicked on they could allow the user to view a screenshot taken at that location.

This could also be helpful for marking cave entrances on the map or the surroundings of locations of hard drives.

**Comment by AnthorNet** [comment]
Care to share some as a starter? Could be something valuable, let's see how it goes ;)

**Comment by SignpostMarv** [comment]
Feature requests like theses is one of the reasons I believe all games with a built-in photomode should embed game coordinates/camera info into the image, cos then you'd be able to programmatically add areas of interest. 🤷‍♂️

**Comment by budak7273** [comment]
I haven't been able to take these screenshots yet, but there have been a few developments since I made this issue request:

- Someone made [a mod](https://ficsit.app/mod/K87bDctxJVMdP) to capture 360 screenshots
- Rex from the Satisfaction Labs team (I think?) made [a website](https://pano.satisfaction-labs.com/maps/lavalamp/) to display them
- Tom from the wiki team sent me a save file a while back with a whole lot of scenic locations marked with beacons. These could be good candidates for places to include photos of. For a previous project, I had built teleporters from the Teleporters mod at every single beacon. I'll attach it here in case anyone else wants to use it.
[scenic_locations_with_teleporters.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/6332453/scenic_locations_with_teleporters.zip)

I think it would be great if the photos shown of the locations were 360 photos. Perhaps you could contact Rex to use the same viewer Satisfaction Labs uses?

**Comment by SignpostMarv** [comment]
> I think it would be great if the photos shown of the locations were 360 photos. Perhaps you could contact Rex to use the same viewer Satisfaction Labs uses?

not if it's only scripted to support full-resolution 8k x 8k tiles 🤷‍♂️
