### ISSUE TITLE
blueprints upload issue

### ISSUE THREAD

**Issue by itsdrwho99** [AnthorNet/SC-InteractiveMap#44]
hello ,,i have a blueprint for a turbofuel powerplant that i built and when i try to upload it to the satisfactory map editor/calculator/ site its stuck on upload , how can i fix it ?
![Capture](https://user-images.githubusercontent.com/75478421/111308730-b9155780-8663-11eb-9b0a-74c55999c896.PNG)

**Comment by AnthorNet** [comment]
Hello,n can you send me the CBP and the blueprint ID/Name?

**Comment by itsdrwho99** [comment]
> 
> 
> Hello,n can you send me the CBP and the blueprint ID/Name?

hi , where can i send it ? here is a link on google drive 
https://drive.google.com/file/d/1HJtngjyswWo3w7oQoW10ESBG97cIpr0c/view?usp=sharing

**Comment by itsdrwho99** [comment]
> 
> 
> Hello,n can you send me the CBP and the blueprint ID/Name?

and here is the name ,, " TurboFuel Powerplant , 44444.4MW from 600 Crude Oil Fully working

**Comment by AnthorNet** [comment]
Blueprint is too big, let me see if I can do anything quickly

**Comment by itsdrwho99** [comment]
> 
> 
> Blueprint is too big, let me see if I can do anything quickly

whats the limit for it and the map picture ?

**Comment by AnthorNet** [comment]
It might be 1mb per default

**Comment by itsdrwho99** [comment]
> 
> 
> It might be 1mb per default

can you increase it ?

**Comment by AnthorNet** [comment]
Fixed to 4mb
