### ISSUE TITLE
Save compiling getting stuck when importing more complex blueprints

### ISSUE THREAD

**Issue by Trilobitaa** [AnthorNet/SC-InteractiveMap#53]
Title. 
It goes up a little more than half and then gets stuck. I tested 'FUBAR's Uranium Subway' and 'Turbo Motor Factory Desert' blueprints. Both tested on Chrome, Opera and Edge. Same results. It managed to import 'simpler' blueprints, like 'Spiral Rail Intersection'.

**Comment by MaxiFik** [comment]
I have the same problem with more blueprints

**Comment by MaridIAudran** [comment]
Also have the same problem. Seems to be throwing JS errors in the Chrome / Edge console - unsure if that's related.
