### ISSUE TITLE
Coal Node Miner Placement Not Showing as Used

### ISSUE THREAD

**Issue by WanderingSilence** [AnthorNet/SC-InteractiveMap#56]
There are 2 pure coal nodes on the north end of the Dune Desert, the symbol for the one to the east doesn't "dim" or "fade" when there is a miner placed on that node. In the attached pic are the 2 nodes side by side, both with miners, you can see the one on the left is faded showing that the node is being used, but the one on the right is still bright as if is it not used.
![image](https://user-images.githubusercontent.com/80968209/112656021-58d2a280-8e27-11eb-8c19-600aea28ccc5.png)

**Comment by AnthorNet** [comment]
Hey, I'll need your save to check the data :)

**Comment by WanderingSilence** [comment]
Here's the file I am currently building on... please don't judge my spaghetti XD I made a zip file since sav files aren't supported.
[Desert Mega Base_260321-115125.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/6212943/Desert.Mega.Base_260321-115125.zip)

**Comment by AnthorNet** [comment]
2 nodes exists at that location :D

**Comment by WanderingSilence** [comment]
so 2 nodes on that same exact spot? so 1 will show as tapped and the other as not?

**Comment by AnthorNet** [comment]
Yes ! :D

**Comment by WanderingSilence** [comment]
Ahh gotcha. Thanks for looking into it! ♥
