### ISSUE TITLE
Space Elevator phase management

### ISSUE THREAD

**Issue by AnthorNet** [AnthorNet/SC-InteractiveMap#6]
- [x] Update space elevator phase
- [x] Delete space elevator
- [x] Ask doggy bag for inner items

**Comment by hejflorian** [comment]
Hi there, just wanted to leave a quick comment: When resetting the space elevator phase, items that have been filled in seem to remain there. When I reset the elevator to the first stage, it still has 50 items in it. Thought I would just leave that here. :) THANKS a million for your awesome job with this project!

**Comment by AnthorNet** [comment]
To be clean it should empty ans ask the user if he wants a doggy crate ;)

**Comment by hejflorian** [comment]
genius, thank you so much!! stay safe, this project is just amazing!

**Comment by hejflorian** [comment]
Just checked and there is no delete option in the context menu. Also, it can't be deleted with the selection tools. It does ask if a doggy bag should be created but it won't disappear after that.

**Comment by AnthorNet** [comment]
Nope it was prohibited like the HUB because it was linked to other game features.
We will now be able to delete it soon ;)
