### ISSUE TITLE
Missing Drop Pod`

### ISSUE THREAD

**Issue by Demiga** [AnthorNet/SC-InteractiveMap#61]
I'm not sure if this has been reported before or if this is the right place to do so:  I found a drop pod that does not show on the interactive map.  

Coords: 174,689 / -277,502
Drop Pod cost: 30 motors

(See attached)

![DropPod](https://user-images.githubusercontent.com/12957437/114322713-afaace00-9aef-11eb-82f9-63afd4f42da7.png)

**Comment by AnthorNet** [comment]
It's only available on Experimental branch
