### ISSUE TITLE
Drawing Tools

### ISSUE THREAD

**Issue by scotlynhatt** [AnthorNet/SC-InteractiveMap#62]
Was watching smerkin5000 draw a honeycomb platform consisting of many hexagons for his latest nuclear setup and thought about the possibility of a grid overlay that could be rotated independently of the map, by degrees (10 or 11.25), which allows placing foundations in each grid space similar to a pixel art process. This would enable drawing complex shapes, both symmetrical and asymmetrical. The user would still need a reference foundation for the grid to align.

Extending the pixel art concept further it would be interesting to see if icon size GIFs could be imported and placed on the grid. Would probably need to limit the XY size of the image to avoid game-breaking foundation counts. Another idea would be the ability to use some sort of pixel brush function to paint directly on the displayed foundations allowing custom coloring or artwork.

FYI, the 11.25 is the Cardinal direction increment if anyone wanted to do things at 45 degrees.

Thank you for reading and for a fantastic application.

**Comment by AnthorNet** [comment]
HAve you tried the Lasso > Fill with ?
