### ISSUE TITLE
Feature Request: Completely hide collected

### ISSUE THREAD

**Issue by SReject** [AnthorNet/SC-InteractiveMap#64]
An option to hide, not just dim, various one-time collectables that have been collected. This would apply to:

- Power Slugs
- Hard Drives/Drop Pods
- Somersloops
- Mercer Spheres

Like wise the ability to hide Resource Nodes and Resource Wells that have a miner/extractor on them

**Comment by AnthorNet** [comment]
I believe most of them were implemented now

**Comment by SReject** [comment]
While the ability to dim the icons for Resource Nodes and Wells have been added, afaik, there's no option to completely hide collectables' icons that have been gathered, nor a way to hide tapped nodes/wells.

To be clear, I'm speaking about when you have a certain collectable/resource shown, I want to be able to completely hide the icons of those that have been collected/tapped while still displaying those that have not.

**Comment by AnthorNet** [comment]
Under map options > Show collected?

**Comment by SReject** [comment]
After tinkering with the options, here's the related info:

Unchecking "Show nodes icons on miners": Dims but does not hide the resource node icon: [The dimmed icons should be hidden](https://i.imgur.com/bxIkHdi.png)

Unchecking "Show Collected Icons" hides artifacts and collectibles(such as bacon shrooms) but does not hide icons for harddrives.

**Comment by AnthorNet** [comment]
Resources node are only working when a save is loaded.
