### ISSUE TITLE
Feature Request: Search function on blueprints page

### ISSUE THREAD

**Issue by archon-valec** [AnthorNet/SC-InteractiveMap#79]
Hello, Now that blueprints are getting popular, and theres 6 pages of them now, would it be possible to implement a search field to search for keywords or tags? i.e. blueprints pertaining to "powerplant" or "turbofuel"... or a resource specific blueprint like oil, coal, or metals... etc...

**Comment by jlellis** [comment]
There are more than 12 pages of them now, and this is definitely becoming a usability issue.  I was looking for examples of nuke plants and never did find one.

**Comment by AnthorNet** [comment]
Added
