### ISSUE TITLE
Feature Request: Decouple the availability of production statistics from map rendering

### ISSUE THREAD

**Issue by SignpostMarv** [AnthorNet/SC-InteractiveMap#82]
Would be nice to be able to click on the statistics panel before the map has finished rendering 😊

**Comment by AnthorNet** [comment]
It's actually not really tied, but the processing taken from rendering the map prevents anything else :D

**Comment by SignpostMarv** [comment]
is it `requestIdleCallback` friendly?

**Comment by AnthorNet** [comment]
Not really, I don't think :p

**Comment by SignpostMarv** [comment]
where's the bit that's locking things up?

**Comment by AnthorNet** [comment]
Rendering the map mostly, even if I use a combination of promise and small timeouts to flush the progress bar.
I can check where the click event is set up see if it's possible to do it earlier.

**Comment by SignpostMarv** [comment]
p.s. I'm wondering if there's anywhere with a loop that this vaguely terrible idea would work:

```js
async function theThingThatLocksUp() {
    // other stuff
    for (let thing of other_thing) {
        await new Promise(requestIdleCallback);
        // the stuff that locks up the thread
    }
    // the rest of the stuff
}
```
