### ISSUE TITLE
Covered Conveyor Belt mod support

### ISSUE THREAD

**Issue by Alien-ufo** [AnthorNet/SC-InteractiveMap#83]
Wrong compatibility and support Covered Conveyor Belt mod.
I use this mod in game but found a strange behavior: after moving some part of the factory buildings & foundations moved well but mods belts not moved.

**Comment by AnthorNet** [comment]
I'll check, it seems the plugin author isn't keeping any norm on naming conventions :D
NOt sure I'll be able to cope with it//

**Comment by Alien-ufo** [comment]
> I'll check, it seems the plugin author isn't keeping any norm on naming conventions :D
> NOt sure I'll be able to cope with it.
So sad. :( 
We believe in you. ;)

**Comment by AnthorNet** [comment]
I can always add exception everywhere but obviously it takes time if you need to handle them all :D
The check is normally donc on a Build_ name as it is with every other building and mods I've seen so far.

**Comment by Alien-ufo** [comment]
I see what are you meaning about:

**original**
- Persistent_Level:PersistentLevel.Build_ConveyorBeltMk5_C_NNNNNN
- Persistent_Level:PersistentLevel.Build_ConveyorLiftMk5_C_NNNNNN
- 
**modded**
- Persistent_Level:PersistentLevel.PCoveredMK7_C_NNNNNN (belt)
- Persistent_Level:PersistentLevel.lift7_C_NNNNNNN (lift)

Such a mess.. O_o

**Comment by AnthorNet** [comment]
Forgot to rebuild and push to production :D

**Comment by Alien-ufo** [comment]
Woohooo!
Thank you very much!
![1620650581944](https://user-images.githubusercontent.com/7453886/117661001-7b860400-b1a6-11eb-852e-b87f9fe7ecb7.png)
Testing functionality with blueprints and shifting (offset)..

**Comment by Alien-ufo** [comment]
Hmmmm.. New issue! :D
![Screenshot20210510-16022200000](https://user-images.githubusercontent.com/7453886/117663421-52b33e00-b1a9-11eb-93b0-62e5f70a65fd.png)
Right side - shifted
Left side - inserted with blueprint

Shifted - is OK.
![Screenshot20210510-16023500000](https://user-images.githubusercontent.com/7453886/117663552-72e2fd00-b1a9-11eb-9071-2df2c5feb27a.png)

The inserted version does not contain belts
![Screenshot20210510-16024300000](https://user-images.githubusercontent.com/7453886/117663604-855d3680-b1a9-11eb-90c8-74a941d9930a.png)

**Comment by AnthorNet** [comment]
Closed for #87 

As it seems that SML have changed the way class are named, so I'll run a big database pass to fix all in one ^^
