### ISSUE TITLE
Buildings from Daisy Chain mod not displaying or being included in BPs

### ISSUE THREAD

**Issue by zimboptoo** [AnthorNet/SC-InteractiveMap#87]
The "Daisy Chain Power Cables" mod is listed as one of the mods supported by SCIM.  However, since Update 4 (and possibly before), the buildings that it adds do not show up in the SCIM map (not even as the "generic modded item" orange square).  They also aren't copied in Blueprints, and thus cannot be pasted back in.  

Daisy Chain Power Cables is currently one of the top downloaded U4 mods, so it seems like a good choice for supporting in the future.

**Comment by AnthorNet** [comment]
Could you link your save please?

**Comment by zimboptoo** [comment]
Of course!  The save is a bit large, but I created a test platform with the HUB nearby, that contains one of each of the vanilla buildings and the Daisy Chain buildings.  The Daisy Chain buildings don't show up in the Interactive Map, and they aren't included in an Offset or Copy function.  

The save has a few other mods installed, so if that doesn't work for you I can put together a "Clean" save with just Daisy Chain and some examples.


[Daisy Chain Test Save.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/6488316/Daisy.Chain.Test.Save.zip)
