### ISSUE TITLE
Color Number Tool

### ISSUE THREAD

**Issue by SMERKIN5000** [AnthorNet/SC-InteractiveMap#9]
Being able to change colors in the save file is great. However a separate tool that allows you to provide RGB values and then SCIM gives you the values to enter into the game color picker would be great.

**Comment by AnthorNet** [comment]
Here you go!
https://satisfactory-calculator.com/en/workbench/color?r=108&g=168&b=212

**Comment by SMERKIN5000** [comment]
Much love 👍
