### ISSUE TITLE
bug report : item of decoration mod not load

### ISSUE THREAD

**Issue by ShinoHarvest** [AnthorNet/SC-InteractiveMap#93]
object of none listed mod in https://satisfactory-calculator.com/fr/mods/index/index/ ex (structural solution) is loaded but mod decoration is listed on https://satisfactory-calculator.com/fr/mods/index/details/p/2/id/18/name/Decoration but it item not load

**Comment by AnthorNet** [comment]
Should load better, that said the FICSIT mod API doesn't return the correct className so apart from manual updates from modders, it's not on my hand
